services:
  - type: web
    name: kwalitec
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    preDeploy: "flask --app wsgi.py db upgrade && flask --app wsgi.py create-admin"
    startCommand: "waitress-serve --port=$PORT wsgi:app"

    envVars:
      - key: APP_ENV
        value: production

      - key: FLASK_APP
        value: wsgi.py

      - key: SECRET_KEY
        generateValue: true

      - key: DATABASE_URL
        fromDatabase:
          name: kwalitec-db
          property: connectionString

databases:
  - name: kwalitec-db
    plan: free