"""Local entry point for the Kwalitec application."""

from __future__ import annotations

import os


def _relocate_werkzeug_debugger_console() -> None:
    """Keep Werkzeug's interactive debugger off ``/console``.

    ``DebuggedApplication`` defaults ``console_path="/console"``, which
    intercepts Founder Console URLs generated by ``url_for`` (no trailing
    slash) before Flask sees them. Relocate the debugger console so
    Kwalitec Console remains reachable under ``flask run --debug``.
    """
    try:
        from werkzeug.debug import DebuggedApplication
    except ImportError:
        return

    if getattr(DebuggedApplication, "_kwalitec_console_path_patched", False):
        return

    original_init = DebuggedApplication.__init__

    def _init(self, *args, **kwargs):  # noqa: ANN001, ANN002, ANN003
        kwargs.setdefault("console_path", "/__debugger__/console")
        return original_init(self, *args, **kwargs)

    DebuggedApplication.__init__ = _init  # type: ignore[method-assign]
    DebuggedApplication._kwalitec_console_path_patched = True  # type: ignore[attr-defined]


_relocate_werkzeug_debugger_console()

from app import create_app  # noqa: E402
from app.models import User  # noqa: E402, F401 - Flask-Migrate model discovery

app = create_app()


if __name__ == "__main__":
    # Prefer PORT (e.g. PaaS), then FLASK_RUN_PORT, then 5001 locally.
    # Default is not 5000: macOS AirPlay Receiver often owns TCP 5000.
    host = os.getenv("FLASK_RUN_HOST", "127.0.0.1")
    port = int(os.getenv("PORT", os.getenv("FLASK_RUN_PORT", 5001)))
    app.run(host=host, port=port, debug=os.environ.get("FLASK_DEBUG", "1") == "1")
