"""Initial Education OS persistence schema.

Revision ID: 202607200001
Revises:
Create Date: 2026-07-20
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = "202607200001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eos_concepts',
    sa.Column('concept_id', sa.String(length=128), nullable=False),
    sa.Column('canonical_name', sa.String(length=256), nullable=False),
    sa.Column('core_meaning', sa.Text(), nullable=False),
    sa.Column('boundary', sa.JSON(), nullable=False),
    sa.Column('learning_objectives', sa.JSON(), nullable=False),
    sa.Column('representations', sa.JSON(), nullable=False),
    sa.Column('misconceptions', sa.JSON(), nullable=False),
    sa.Column('application_contexts', sa.JSON(), nullable=False),
    sa.Column('transfer_contexts', sa.JSON(), nullable=False),
    sa.Column('dependencies', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('concept_id', name=op.f('pk_eos_concepts'))
    )
    op.create_table('eos_decisions',
    sa.Column('decision_id', sa.String(length=128), nullable=False),
    sa.Column('student_id', sa.String(length=128), nullable=False),
    sa.Column('priority_references', sa.JSON(), nullable=False),
    sa.Column('intention_references', sa.JSON(), nullable=False),
    sa.Column('strategy_references', sa.JSON(), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('constraints', sa.JSON(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.JSON(), nullable=False),
    sa.Column('readiness', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=64), nullable=True),
    sa.Column('reconsideration_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('decision_id', name=op.f('pk_eos_decisions'))
    )
    op.create_index(op.f('ix_eos_decisions_student_id'), 'eos_decisions', ['student_id'], unique=False)
    op.create_table('eos_diagnoses',
    sa.Column('diagnosis_id', sa.String(length=128), nullable=False),
    sa.Column('student_id', sa.String(length=128), nullable=False),
    sa.Column('diagnosis_type', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.JSON(), nullable=False),
    sa.Column('severity', sa.JSON(), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('known_evidence_ids', sa.JSON(), nullable=False),
    sa.Column('known_interpretation_ids', sa.JSON(), nullable=False),
    sa.Column('interpretation_references', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('invalidation_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('diagnosis_id', name=op.f('pk_eos_diagnoses'))
    )
    op.create_index(op.f('ix_eos_diagnoses_student_id'), 'eos_diagnoses', ['student_id'], unique=False)
    op.create_table('eos_digital_twins',
    sa.Column('twin_id', sa.String(length=128), nullable=False),
    sa.Column('student_id', sa.String(length=128), nullable=False),
    sa.Column('learner_state', sa.JSON(), nullable=False),
    sa.Column('concept_states', sa.JSON(), nullable=False),
    sa.Column('misconception_states', sa.JSON(), nullable=False),
    sa.Column('evidence_history', sa.JSON(), nullable=False),
    sa.Column('intervention_history', sa.JSON(), nullable=False),
    sa.Column('retention', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.JSON(), nullable=False),
    sa.Column('trajectory', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('twin_id', name=op.f('pk_eos_digital_twins'))
    )
    op.create_index(op.f('ix_eos_digital_twins_student_id'), 'eos_digital_twins', ['student_id'], unique=False)
    op.create_table('eos_evidence_records',
    sa.Column('evidence_id', sa.String(length=128), nullable=False),
    sa.Column('student_id', sa.String(length=128), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('source', sa.JSON(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.JSON(), nullable=False),
    sa.Column('strength', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.String(length=64), nullable=False),
    sa.Column('known_concept_ids', sa.JSON(), nullable=False),
    sa.Column('known_episode_ids', sa.JSON(), nullable=False),
    sa.Column('concept_references', sa.JSON(), nullable=False),
    sa.Column('learning_episode_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('invalidation_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('evidence_id', name=op.f('pk_eos_evidence_records'))
    )
    op.create_index(op.f('ix_eos_evidence_records_student_id'), 'eos_evidence_records', ['student_id'], unique=False)
    op.create_table('eos_hypotheses',
    sa.Column('hypothesis_id', sa.String(length=128), nullable=False),
    sa.Column('student_id', sa.String(length=128), nullable=False),
    sa.Column('hypothesis_kind', sa.String(length=64), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('plausibility', sa.JSON(), nullable=False),
    sa.Column('explanatory_strength', sa.JSON(), nullable=False),
    sa.Column('diagnosis_references', sa.JSON(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('interpretation_references', sa.JSON(), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('competing_hypotheses', sa.JSON(), nullable=False),
    sa.Column('known_evidence_ids', sa.JSON(), nullable=False),
    sa.Column('known_interpretation_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('discard_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('hypothesis_id', name=op.f('pk_eos_hypotheses'))
    )
    op.create_index(op.f('ix_eos_hypotheses_student_id'), 'eos_hypotheses', ['student_id'], unique=False)
    op.create_table('eos_learning_episodes',
    sa.Column('episode_id', sa.String(length=128), nullable=False),
    sa.Column('student_id', sa.String(length=128), nullable=False),
    sa.Column('teaching_goal', sa.JSON(), nullable=False),
    sa.Column('teaching_strategy_id', sa.String(length=128), nullable=False),
    sa.Column('learning_objectives', sa.JSON(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('concept_references', sa.JSON(), nullable=False),
    sa.Column('primary_dimension', sa.String(length=64), nullable=False),
    sa.Column('duration', sa.JSON(), nullable=True),
    sa.Column('selection_rationale', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('reflection', sa.JSON(), nullable=True),
    sa.Column('outcome', sa.JSON(), nullable=True),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('episode_id', name=op.f('pk_eos_learning_episodes'))
    )
    op.create_index(op.f('ix_eos_learning_episodes_student_id'), 'eos_learning_episodes', ['student_id'], unique=False)
    op.create_table('eos_orchestrators',
    sa.Column('orchestrator_id', sa.String(length=128), nullable=False),
    sa.Column('student_id', sa.String(length=128), nullable=False),
    sa.Column('decision_reference', sa.JSON(), nullable=False),
    sa.Column('strategy_references', sa.JSON(), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=False),
    sa.Column('episode_references', sa.JSON(), nullable=False),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('orchestrator_id', name=op.f('pk_eos_orchestrators'))
    )
    op.create_index(op.f('ix_eos_orchestrators_student_id'), 'eos_orchestrators', ['student_id'], unique=False)
    op.create_table('eos_priorities',
    sa.Column('priority_id', sa.String(length=128), nullable=False),
    sa.Column('student_id', sa.String(length=128), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('diagnosis_references', sa.JSON(), nullable=False),
    sa.Column('hypothesis_references', sa.JSON(), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('score', sa.JSON(), nullable=False),
    sa.Column('urgency', sa.JSON(), nullable=False),
    sa.Column('instructional_impact', sa.JSON(), nullable=False),
    sa.Column('constraints', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('stabilisation_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('priority_id', name=op.f('pk_eos_priorities'))
    )
    op.create_index(op.f('ix_eos_priorities_student_id'), 'eos_priorities', ['student_id'], unique=False)
    op.create_table('eos_teaching_intentions',
    sa.Column('intention_id', sa.String(length=128), nullable=False),
    sa.Column('student_id', sa.String(length=128), nullable=False),
    sa.Column('intention_type', sa.String(length=64), nullable=False),
    sa.Column('goal', sa.JSON(), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('expected_outcome', sa.JSON(), nullable=False),
    sa.Column('strength', sa.JSON(), nullable=False),
    sa.Column('priority_references', sa.JSON(), nullable=False),
    sa.Column('diagnosis_references', sa.JSON(), nullable=False),
    sa.Column('hypothesis_references', sa.JSON(), nullable=False),
    sa.Column('constraints', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('retire_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('intention_id', name=op.f('pk_eos_teaching_intentions'))
    )
    op.create_index(op.f('ix_eos_teaching_intentions_student_id'), 'eos_teaching_intentions', ['student_id'], unique=False)
    op.create_table('eos_teaching_plans',
    sa.Column('plan_id', sa.String(length=128), nullable=False),
    sa.Column('episode_id', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('plan_id', name=op.f('pk_eos_teaching_plans'))
    )
    op.create_index(op.f('ix_eos_teaching_plans_episode_id'), 'eos_teaching_plans', ['episode_id'], unique=True)
    op.create_table('eos_teaching_strategies',
    sa.Column('strategy_id', sa.String(length=128), nullable=False),
    sa.Column('student_id', sa.String(length=128), nullable=False),
    sa.Column('primary_strategy', sa.String(length=64), nullable=False),
    sa.Column('goal', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.JSON(), nullable=False),
    sa.Column('effectiveness', sa.JSON(), nullable=False),
    sa.Column('complexity', sa.JSON(), nullable=False),
    sa.Column('intention_references', sa.JSON(), nullable=False),
    sa.Column('diagnosis_references', sa.JSON(), nullable=False),
    sa.Column('hypothesis_references', sa.JSON(), nullable=False),
    sa.Column('secondary_strategies', sa.JSON(), nullable=False),
    sa.Column('constraints', sa.JSON(), nullable=False),
    sa.Column('composition_pattern', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('retire_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('strategy_id', name=op.f('pk_eos_teaching_strategies'))
    )
    op.create_index(op.f('ix_eos_teaching_strategies_student_id'), 'eos_teaching_strategies', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eos_teaching_strategies_student_id'), table_name='eos_teaching_strategies')
    op.drop_table('eos_teaching_strategies')
    op.drop_index(op.f('ix_eos_teaching_plans_episode_id'), table_name='eos_teaching_plans')
    op.drop_table('eos_teaching_plans')
    op.drop_index(op.f('ix_eos_teaching_intentions_student_id'), table_name='eos_teaching_intentions')
    op.drop_table('eos_teaching_intentions')
    op.drop_index(op.f('ix_eos_priorities_student_id'), table_name='eos_priorities')
    op.drop_table('eos_priorities')
    op.drop_index(op.f('ix_eos_orchestrators_student_id'), table_name='eos_orchestrators')
    op.drop_table('eos_orchestrators')
    op.drop_index(op.f('ix_eos_learning_episodes_student_id'), table_name='eos_learning_episodes')
    op.drop_table('eos_learning_episodes')
    op.drop_index(op.f('ix_eos_hypotheses_student_id'), table_name='eos_hypotheses')
    op.drop_table('eos_hypotheses')
    op.drop_index(op.f('ix_eos_evidence_records_student_id'), table_name='eos_evidence_records')
    op.drop_table('eos_evidence_records')
    op.drop_index(op.f('ix_eos_digital_twins_student_id'), table_name='eos_digital_twins')
    op.drop_table('eos_digital_twins')
    op.drop_index(op.f('ix_eos_diagnoses_student_id'), table_name='eos_diagnoses')
    op.drop_table('eos_diagnoses')
    op.drop_index(op.f('ix_eos_decisions_student_id'), table_name='eos_decisions')
    op.drop_table('eos_decisions')
    op.drop_table('eos_concepts')
    # ### end Alembic commands ###
