"""Curriculum Intelligence Pipeline (CIP) + Engine (EI-001) domain package.

Bounded context for transforming uploaded curriculum PDFs into structured
educational knowledge that powers the Student Digital Twin roadmap.

CIP-001: extraction → map → graph.
CIP-002: provenance, confidence, validation, Founder review, audit.
EI-001: multi-generation Curriculum Intelligence Engine contracts.
No LLM. No embeddings. No OCR. No student-facing recommendation logic.
"""

from __future__ import annotations

from typing import Any

__all__ = [
    "AgentDescriptor",
    "AuditAction",
    "AuditEvent",
    "BlockKind",
    "AdaptiveLearningPlan",
    "AdaptiveLearningSignal",
    "CalibrationProfile",
    "CertificationDecision",
    "CertificationOutcome",
    "CertificationPolicy",
    "CertificationReport",
    "CertifiedCurriculumSnapshot",
    "CertifiedMissionSpec",
    "CertifiedNodeKind",
    "CertifiedProgressSnapshot",
    "CertifiedTutorContext",
    "ConfidenceBand",
    "CurriculumObservatoryReport",
    "CurriculumProvenanceRef",
    "ConfidenceFactor",
    "ConfidenceRecord",
    "CurriculumEntityKind",
    "CurriculumGenerationSnapshot",
    "CurriculumKnowledgeEntity",
    "CurriculumMap",
    "DecisionLedgerEntry",
    "DecisionLedgerSummary",
    "DecisionOutcome",
    "DecisionQualityScores",
    "DecisionType",
    "DifficultyBiasStyle",
    "ENTITY_CHILD_KINDS",
    "EducationalNode",
    "EducationalReviewPack",
    "EvidenceGrade",
    "ExtractedBlock",
    "ExtractedDocument",
    "ExtractedPage",
    "FOUNDER_PIPELINE_MILESTONES",
    "FOUNDER_STAGE_LABELS",
    "GENERATION_PURPOSES",
    "GRAPH_BUILDER_VERSION",
    "Generation",
    "GenerationComparisonRow",
    "GenerationIndex",
    "GranularityStyle",
    "HierarchyStyle",
    "KnowledgeGraph",
    "KnowledgeRelation",
    "KnowledgeRelationType",
    "LearnerGraphEdge",
    "LearnerGraphNode",
    "LearnerKnowledgeGraph",
    "LineageOperation",
    "LineageOperationKind",
    "LineageRecord",
    "MAPPER_VERSION",
    "MissionSelectionReason",
    "NodeMasteryRecord",
    "ObservatoryMetric",
    "PARSER_VERSION",
    "PIPELINE_ORDER",
    "PipelineQualityMetrics",
    "PipelineStage",
    "PipelineTransitionEvent",
    "PolicyDescriptor",
    "ProvenanceChainStage",
    "ProvenanceRecord",
    "ProvenanceSubjectKind",
    "QualitySnapshot",
    "RegressionPolicy",
    "RegressionReport",
    "RejectedNode",
    "ReviewDecision",
    "ReviewRecord",
    "ReviewStatus",
    "STANDARD_QUALITY_METRICS",
    "SnapshotStatus",
    "StructuralDocument",
    "StructuralKind",
    "StructuralNode",
    "SupportingEvidence",
    "TopicDensityStyle",
    "ValidationIssue",
    "ValidationIssueKind",
    "ValidationReport",
    "ValidationSeverity",
    "VerificationStatus",
    "best_evidence_grade",
    "confidence_band_from_score",
    "evidence_grade_weight",
    "founder_label",
    "has_reached",
    "infer_decision_type",
    "is_failure",
    "is_terminal",
    "ledger_entry_from_educational_decision",
    "next_pipeline_stage",
    "pipeline_index",
    "purpose_for_index",
    "resolve_pipeline_stage",
    "resume_stage_after_failure",
]

_CL = "app.domain.curriculum_intelligence.certified_learning"

_EXPORT_MODULES = {
    "AgentDescriptor": "app.domain.curriculum_intelligence.agent",
    "STANDARD_QUALITY_METRICS": "app.domain.curriculum_intelligence.agent",
    "BlockKind": "app.domain.curriculum_intelligence.extracted_document",
    "ExtractedBlock": "app.domain.curriculum_intelligence.extracted_document",
    "ExtractedDocument": "app.domain.curriculum_intelligence.extracted_document",
    "ExtractedPage": "app.domain.curriculum_intelligence.extracted_document",
    "StructuralKind": "app.domain.curriculum_intelligence.structural_document",
    "StructuralNode": "app.domain.curriculum_intelligence.structural_document",
    "StructuralDocument": "app.domain.curriculum_intelligence.structural_document",
    "CurriculumEntityKind": "app.domain.curriculum_intelligence.curriculum_entity",
    "CurriculumKnowledgeEntity": "app.domain.curriculum_intelligence.curriculum_entity",
    "CurriculumMap": "app.domain.curriculum_intelligence.curriculum_entity",
    "ENTITY_CHILD_KINDS": "app.domain.curriculum_intelligence.curriculum_entity",
    "KnowledgeRelationType": "app.domain.curriculum_intelligence.knowledge_graph",
    "KnowledgeRelation": "app.domain.curriculum_intelligence.knowledge_graph",
    "KnowledgeGraph": "app.domain.curriculum_intelligence.knowledge_graph",
    "PipelineStage": "app.domain.curriculum_intelligence.pipeline_stage",
    "PipelineTransitionEvent": "app.domain.curriculum_intelligence.pipeline_stage",
    "PIPELINE_ORDER": "app.domain.curriculum_intelligence.pipeline_stage",
    "FOUNDER_PIPELINE_MILESTONES": "app.domain.curriculum_intelligence.pipeline_stage",
    "FOUNDER_STAGE_LABELS": "app.domain.curriculum_intelligence.pipeline_stage",
    "founder_label": "app.domain.curriculum_intelligence.pipeline_stage",
    "has_reached": "app.domain.curriculum_intelligence.pipeline_stage",
    "is_failure": "app.domain.curriculum_intelligence.pipeline_stage",
    "is_terminal": "app.domain.curriculum_intelligence.pipeline_stage",
    "next_pipeline_stage": "app.domain.curriculum_intelligence.pipeline_stage",
    "pipeline_index": "app.domain.curriculum_intelligence.pipeline_stage",
    "resolve_pipeline_stage": "app.domain.curriculum_intelligence.pipeline_stage",
    "resume_stage_after_failure": "app.domain.curriculum_intelligence.pipeline_stage",
    "PARSER_VERSION": "app.domain.curriculum_intelligence.provenance",
    "MAPPER_VERSION": "app.domain.curriculum_intelligence.provenance",
    "GRAPH_BUILDER_VERSION": "app.domain.curriculum_intelligence.provenance",
    "ProvenanceSubjectKind": "app.domain.curriculum_intelligence.provenance",
    "ProvenanceChainStage": "app.domain.curriculum_intelligence.provenance",
    "SupportingEvidence": "app.domain.curriculum_intelligence.provenance",
    "ProvenanceRecord": "app.domain.curriculum_intelligence.provenance",
    "ConfidenceBand": "app.domain.curriculum_intelligence.confidence",
    "ConfidenceFactor": "app.domain.curriculum_intelligence.confidence",
    "ConfidenceRecord": "app.domain.curriculum_intelligence.confidence",
    "confidence_band_from_score": "app.domain.curriculum_intelligence.confidence",
    "ReviewStatus": "app.domain.curriculum_intelligence.review",
    "VerificationStatus": "app.domain.curriculum_intelligence.review",
    "ReviewDecision": "app.domain.curriculum_intelligence.review",
    "ReviewRecord": "app.domain.curriculum_intelligence.review",
    "AuditAction": "app.domain.curriculum_intelligence.audit",
    "AuditEvent": "app.domain.curriculum_intelligence.audit",
    "ValidationIssueKind": "app.domain.curriculum_intelligence.validation_report",
    "ValidationSeverity": "app.domain.curriculum_intelligence.validation_report",
    "ValidationIssue": "app.domain.curriculum_intelligence.validation_report",
    "ValidationReport": "app.domain.curriculum_intelligence.validation_report",
    "PipelineQualityMetrics": "app.domain.curriculum_intelligence.quality_metrics",
    "GenerationIndex": "app.domain.curriculum_intelligence.generation",
    "GENERATION_PURPOSES": "app.domain.curriculum_intelligence.generation",
    "SnapshotStatus": "app.domain.curriculum_intelligence.generation",
    "LineageOperationKind": "app.domain.curriculum_intelligence.generation",
    "CertificationOutcome": "app.domain.curriculum_intelligence.generation",
    "GranularityStyle": "app.domain.curriculum_intelligence.generation",
    "HierarchyStyle": "app.domain.curriculum_intelligence.generation",
    "TopicDensityStyle": "app.domain.curriculum_intelligence.generation",
    "DifficultyBiasStyle": "app.domain.curriculum_intelligence.generation",
    "LineageOperation": "app.domain.curriculum_intelligence.generation",
    "LineageRecord": "app.domain.curriculum_intelligence.generation",
    "EducationalNode": "app.domain.curriculum_intelligence.generation",
    "RejectedNode": "app.domain.curriculum_intelligence.generation",
    "QualitySnapshot": "app.domain.curriculum_intelligence.generation",
    "RegressionPolicy": "app.domain.curriculum_intelligence.generation",
    "RegressionReport": "app.domain.curriculum_intelligence.generation",
    "Generation": "app.domain.curriculum_intelligence.generation",
    "CurriculumGenerationSnapshot": "app.domain.curriculum_intelligence.generation",
    "CertificationDecision": "app.domain.curriculum_intelligence.generation",
    "CalibrationProfile": "app.domain.curriculum_intelligence.generation",
    "purpose_for_index": "app.domain.curriculum_intelligence.generation",
    "EvidenceGrade": "app.domain.curriculum_intelligence.evidence",
    "best_evidence_grade": "app.domain.curriculum_intelligence.evidence",
    "evidence_grade_weight": "app.domain.curriculum_intelligence.evidence",
    "PolicyDescriptor": "app.domain.curriculum_intelligence.policy",
    "DecisionType": "app.domain.curriculum_intelligence.decision_ledger",
    "DecisionOutcome": "app.domain.curriculum_intelligence.decision_ledger",
    "DecisionLedgerEntry": "app.domain.curriculum_intelligence.decision_ledger",
    "DecisionLedgerSummary": "app.domain.curriculum_intelligence.decision_ledger",
    "infer_decision_type": "app.domain.curriculum_intelligence.decision_ledger",
    "ledger_entry_from_educational_decision": (
        "app.domain.curriculum_intelligence.decision_ledger"
    ),
    "CertificationPolicy": "app.domain.curriculum_intelligence.certification",
    "DecisionQualityScores": "app.domain.curriculum_intelligence.certification",
    "CertificationReport": "app.domain.curriculum_intelligence.certification",
    "CertifiedCurriculumSnapshot": "app.domain.curriculum_intelligence.certification",
    "AdaptiveLearningPlan": _CL,
    "AdaptiveLearningSignal": _CL,
    "CertifiedMissionSpec": _CL,
    "CertifiedNodeKind": _CL,
    "CertifiedProgressSnapshot": _CL,
    "CertifiedTutorContext": _CL,
    "CurriculumObservatoryReport": _CL,
    "CurriculumProvenanceRef": _CL,
    "LearnerGraphEdge": _CL,
    "LearnerGraphNode": _CL,
    "LearnerKnowledgeGraph": _CL,
    "MissionSelectionReason": _CL,
    "NodeMasteryRecord": _CL,
    "ObservatoryMetric": _CL,
    "GenerationComparisonRow": "app.domain.curriculum_intelligence.review_pack",
    "EducationalReviewPack": "app.domain.curriculum_intelligence.review_pack",
}


def __getattr__(name: str) -> Any:
    module_name = _EXPORT_MODULES.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    from importlib import import_module

    module = import_module(module_name)
    value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
