"""Assessment Engine bounded context — domain foundation (AP-002A/C).

Pure educational domain model for assessment as evidence collection.
No persistence, Flask, SQLAlchemy, Twin writes, Reasoning, Mission, Tutor,
or delivery UX.
"""

from __future__ import annotations

from domain.assessment.aggregation import ObservationAggregator, ObservationCollection
from domain.assessment.entities import (
    AssessmentAttempt,
    AssessmentInstrument,
    AssessmentObservation,
    AssessmentQuestionReference,
    AssessmentResult,
    AssessmentSession,
)
from domain.assessment.enums import (
    AssessmentPurpose,
    AssessmentStatus,
    AssessmentType,
    AttemptOutcome,
    ConfidenceBand,
    DifficultyBand,
    EvidenceSource,
    EvidenceStrengthBand,
    HintPolicy,
    ItemType,
    KnowledgeLevel,
    ObservationKind,
    RetryPolicy,
)
from domain.assessment.events import (
    AssessmentEvidenceCreated,
    AssessmentObservationRecorded,
    AssessmentResponseCommitted,
    AssessmentSessionClosed,
    AssessmentSessionConstructed,
    AssessmentSessionStarted,
    AssessmentSessionSubmitted,
    EvidencePackaged,
    EvidenceValidated,
)
from domain.assessment.evidence import (
    PACKAGING_VERSION,
    EvidenceBundle,
    EvidenceBundleId,
    EvidenceContext,
    EvidenceItem,
    EvidenceItemId,
    EvidenceMetadata,
    EvidencePackagingResult,
    EvidenceReference,
    EvidenceSummary,
)
from domain.assessment.exceptions import (
    AssessmentDomainError,
    AssessmentInvariantViolation,
    DuplicateQuestionReferenceError,
    InvalidAssessmentStateTransition,
    InvalidConfidenceRangeError,
    InvalidObservationPayloadError,
    MissingLearningObjectiveError,
)
from domain.assessment.factories import (
    AssessmentInstrumentFactory,
    AssessmentObservationFactory,
    AssessmentResultFactory,
    AssessmentSessionFactory,
)
from domain.assessment.packaging import (
    EvidenceBundleBuilder,
    EvidencePackager,
    EvidenceStrengthFactors,
    calculate_evidence_strength,
    derive_strength_factors,
    package_observations,
)
from domain.assessment.validation import (
    ALLOWED_TRANSITIONS,
    assert_can_transition,
    can_transition,
)
from domain.assessment.value_objects import (
    AssessmentConfiguration,
    AssessmentId,
    AssessmentMetadata,
    AttemptNumber,
    ConceptId,
    ConceptReference,
    ConfidenceLevel,
    DifficultyLevel,
    EvidenceDimensions,
    EvidenceStrength,
    InstrumentId,
    LearningObjectiveId,
    LearningObjectiveReference,
    ObservationId,
    QuestionId,
    QuestionReference,
    ResultId,
    SessionId,
)

__all__ = [
    "ALLOWED_TRANSITIONS",
    "PACKAGING_VERSION",
    "AssessmentAttempt",
    "AssessmentConfiguration",
    "AssessmentDomainError",
    "AssessmentEvidenceCreated",
    "AssessmentId",
    "AssessmentInstrument",
    "AssessmentInstrumentFactory",
    "AssessmentInvariantViolation",
    "AssessmentMetadata",
    "AssessmentObservation",
    "AssessmentObservationFactory",
    "AssessmentObservationRecorded",
    "AssessmentPurpose",
    "AssessmentQuestionReference",
    "AssessmentResponseCommitted",
    "AssessmentResult",
    "AssessmentResultFactory",
    "AssessmentSession",
    "AssessmentSessionClosed",
    "AssessmentSessionConstructed",
    "AssessmentSessionFactory",
    "AssessmentSessionStarted",
    "AssessmentSessionSubmitted",
    "AssessmentStatus",
    "AssessmentType",
    "AttemptNumber",
    "AttemptOutcome",
    "ConceptId",
    "ConceptReference",
    "ConfidenceBand",
    "ConfidenceLevel",
    "DifficultyBand",
    "DifficultyLevel",
    "DuplicateQuestionReferenceError",
    "EvidenceBundle",
    "EvidenceBundleBuilder",
    "EvidenceBundleId",
    "EvidenceContext",
    "EvidenceDimensions",
    "EvidenceItem",
    "EvidenceItemId",
    "EvidenceMetadata",
    "EvidencePackaged",
    "EvidencePackager",
    "EvidencePackagingResult",
    "EvidenceReference",
    "EvidenceSource",
    "EvidenceStrength",
    "EvidenceStrengthBand",
    "EvidenceStrengthFactors",
    "EvidenceSummary",
    "EvidenceValidated",
    "HintPolicy",
    "InstrumentId",
    "InvalidAssessmentStateTransition",
    "InvalidConfidenceRangeError",
    "InvalidObservationPayloadError",
    "ItemType",
    "KnowledgeLevel",
    "LearningObjectiveId",
    "LearningObjectiveReference",
    "MissingLearningObjectiveError",
    "ObservationAggregator",
    "ObservationCollection",
    "ObservationId",
    "ObservationKind",
    "QuestionId",
    "QuestionReference",
    "ResultId",
    "RetryPolicy",
    "SessionId",
    "assert_can_transition",
    "calculate_evidence_strength",
    "can_transition",
    "derive_strength_factors",
    "package_observations",
]
