"""Assessment Engine bounded context — domain foundation (AP-002A).

Pure educational domain model for assessment as evidence collection.
No persistence, Flask, SQLAlchemy, Twin writes, Reasoning, Mission, Tutor,
or delivery UX.
"""

from __future__ import annotations

from domain.assessment.entities import (
    AssessmentAttempt,
    AssessmentInstrument,
    AssessmentObservation,
    AssessmentQuestionReference,
    AssessmentResult,
    AssessmentSession,
)
from domain.assessment.enums import (
    AssessmentPurpose,
    AssessmentStatus,
    AssessmentType,
    AttemptOutcome,
    ConfidenceBand,
    DifficultyBand,
    EvidenceSource,
    EvidenceStrengthBand,
    HintPolicy,
    ItemType,
    KnowledgeLevel,
    ObservationKind,
    RetryPolicy,
)
from domain.assessment.events import (
    AssessmentObservationRecorded,
    AssessmentResponseCommitted,
    AssessmentSessionClosed,
    AssessmentSessionConstructed,
    AssessmentSessionStarted,
    AssessmentSessionSubmitted,
)
from domain.assessment.exceptions import (
    AssessmentDomainError,
    AssessmentInvariantViolation,
    DuplicateQuestionReferenceError,
    InvalidAssessmentStateTransition,
    InvalidConfidenceRangeError,
    InvalidObservationPayloadError,
    MissingLearningObjectiveError,
)
from domain.assessment.factories import (
    AssessmentInstrumentFactory,
    AssessmentObservationFactory,
    AssessmentResultFactory,
    AssessmentSessionFactory,
)
from domain.assessment.validation import (
    ALLOWED_TRANSITIONS,
    assert_can_transition,
    can_transition,
)
from domain.assessment.value_objects import (
    AssessmentConfiguration,
    AssessmentId,
    AssessmentMetadata,
    AttemptNumber,
    ConceptId,
    ConceptReference,
    ConfidenceLevel,
    DifficultyLevel,
    EvidenceDimensions,
    EvidenceStrength,
    InstrumentId,
    LearningObjectiveId,
    LearningObjectiveReference,
    ObservationId,
    QuestionId,
    QuestionReference,
    ResultId,
    SessionId,
)

__all__ = [
    "ALLOWED_TRANSITIONS",
    "AssessmentAttempt",
    "AssessmentConfiguration",
    "AssessmentDomainError",
    "AssessmentId",
    "AssessmentInstrument",
    "AssessmentInstrumentFactory",
    "AssessmentInvariantViolation",
    "AssessmentMetadata",
    "AssessmentObservation",
    "AssessmentObservationFactory",
    "AssessmentObservationRecorded",
    "AssessmentPurpose",
    "AssessmentQuestionReference",
    "AssessmentResponseCommitted",
    "AssessmentResult",
    "AssessmentResultFactory",
    "AssessmentSession",
    "AssessmentSessionClosed",
    "AssessmentSessionConstructed",
    "AssessmentSessionFactory",
    "AssessmentSessionStarted",
    "AssessmentSessionSubmitted",
    "AssessmentStatus",
    "AssessmentType",
    "AttemptNumber",
    "AttemptOutcome",
    "ConceptId",
    "ConceptReference",
    "ConfidenceBand",
    "ConfidenceLevel",
    "DifficultyBand",
    "DifficultyLevel",
    "DuplicateQuestionReferenceError",
    "EvidenceDimensions",
    "EvidenceSource",
    "EvidenceStrength",
    "EvidenceStrengthBand",
    "HintPolicy",
    "InstrumentId",
    "InvalidAssessmentStateTransition",
    "InvalidConfidenceRangeError",
    "InvalidObservationPayloadError",
    "ItemType",
    "KnowledgeLevel",
    "LearningObjectiveId",
    "LearningObjectiveReference",
    "MissingLearningObjectiveError",
    "ObservationId",
    "ObservationKind",
    "QuestionId",
    "QuestionReference",
    "ResultId",
    "RetryPolicy",
    "SessionId",
    "assert_can_transition",
    "can_transition",
]
