"""Kwalitec V3 Design System — framework-independent visual language.

Token catalogue and pure component contracts for Version 3 surfaces.
No business logic. No educational logic. No Flask-specific styling.
"""

from __future__ import annotations

from presentation.design_system.colours import (
    BRAND_COLOURS,
    SEMANTIC_COLOURS,
    BrandColour,
    ColourValue,
    SemanticColour,
    colour,
)
from presentation.design_system.components import (
    Accordion,
    AccordionPanel,
    Badge,
    Button,
    ButtonVariant,
    Card,
    CardVariant,
    Chip,
    Divider,
    EmptyState,
    LoadingState,
    MissionCard,
    Modal,
    PageHeader,
    ProgressBar,
    ProgressCard,
    ProgressRing,
    RecommendationCard,
    Section,
    Skeleton,
    SkeletonVariant,
    StatisticTile,
    Stepper,
    StepperStep,
    Tag,
    Timeline,
    TimelineItem,
    Toast,
    ToastTone,
    Tone,
    danger_button,
    ghost_button,
    primary_button,
    secondary_button,
)
from presentation.design_system.contrast import contrast_ratio, meets_contrast
from presentation.design_system.design_tokens import TOKENS, DesignTokens, get_tokens
from presentation.design_system.elevation import ELEVATION, ElevationToken, elevation
from presentation.design_system.icons import ICON_LIBRARY, IconName, IconSize, IconSpec
from presentation.design_system.layout import (
    BREAKPOINTS,
    CONTAINERS,
    DESKTOP_GRID,
    GRIDS,
    MOBILE_GRID,
    TABLET_GRID,
    Breakpoint,
    ContainerWidth,
    GridSpec,
    breakpoint_at_width,
    columns_at_width,
    container,
    grid_for,
)
from presentation.design_system.motion import MOTION, MotionToken, motion
from presentation.design_system.radius import RADIUS, RadiusToken, radius
from presentation.design_system.spacing import SPACING, SpacingToken, space
from presentation.design_system.typography import TYPE_STYLES, TypeRole, type_style

__all__ = [
    "BRAND_COLOURS",
    "BREAKPOINTS",
    "CONTAINERS",
    "DESKTOP_GRID",
    "ELEVATION",
    "GRIDS",
    "ICON_LIBRARY",
    "MOBILE_GRID",
    "MOTION",
    "RADIUS",
    "SEMANTIC_COLOURS",
    "SPACING",
    "TABLET_GRID",
    "TOKENS",
    "TYPE_STYLES",
    "Accordion",
    "AccordionPanel",
    "Badge",
    "BrandColour",
    "Breakpoint",
    "Button",
    "ButtonVariant",
    "Card",
    "CardVariant",
    "Chip",
    "ColourValue",
    "ContainerWidth",
    "DesignTokens",
    "Divider",
    "ElevationToken",
    "EmptyState",
    "GridSpec",
    "IconName",
    "IconSize",
    "IconSpec",
    "LoadingState",
    "MissionCard",
    "Modal",
    "MotionToken",
    "PageHeader",
    "ProgressBar",
    "ProgressCard",
    "ProgressRing",
    "RadiusToken",
    "RecommendationCard",
    "Section",
    "SemanticColour",
    "Skeleton",
    "SkeletonVariant",
    "SpacingToken",
    "StatisticTile",
    "Stepper",
    "StepperStep",
    "Tag",
    "Timeline",
    "TimelineItem",
    "Toast",
    "ToastTone",
    "Tone",
    "TypeRole",
    "breakpoint_at_width",
    "colour",
    "columns_at_width",
    "container",
    "contrast_ratio",
    "danger_button",
    "elevation",
    "get_tokens",
    "ghost_button",
    "grid_for",
    "meets_contrast",
    "motion",
    "primary_button",
    "radius",
    "secondary_button",
    "space",
    "type_style",
]
