"""Evidence Platform Adapter package (MS-006 E0 / E1 / E2 / E3 / E4 / E5).

Contracts, DTOs, EvidenceCollector, EvidenceAssembler, EvidenceValidator,
EvidenceFactory, collection telemetry, ExperimentFramework,
ExperimentAssigner, ExperimentDefinitionRegistry, ExperimentValidator,
experiment telemetry, PolicyEvaluator, EvaluationAssembler,
EvaluationValidator, EvaluationExplainability, PolicyEvaluationFactory,
evaluation telemetry, AnalyticsEngine, AnalyticsAggregator,
EvidenceProjector, EvidenceProjectionPort, analytics telemetry,
EvidenceShadowValidator, DeterminismValidator, ReadinessEvaluator,
OperationalHealthMonitor, RollbackController, shadow telemetry, and
EvidenceAdapter DI. Feature flag ``KWALITEC_EVIDENCE_PLATFORM`` /
``ENABLE_EVIDENCE_PLATFORM`` defaults OFF. No persistence, policy
promotion, Runtime A writes, Twin mutation, Adaptive re-ranking, Strategy
mutation, or Experience authority cutover.
"""

from __future__ import annotations

from .adapter import (
    EvidencePlatformAdapter,
    build_evidence_platform_adapter,
    empty_evidence_record,
)
from .advisory_assembler import (
    DEFAULT_SOURCE_DESCRIPTION as ADVISORY_SOURCE_DESCRIPTION,
)
from .advisory_assembler import (
    SOURCE_SERVICE as ADVISORY_SOURCE_SERVICE,
)
from .advisory_assembler import (
    EvidenceAdvisoryAssembler,
    build_evidence_advisory_assembler,
    deterministic_advisory_id,
    format_period_source_description,
)
from .aggregator import (
    AnalyticsAggregator,
    AnalyticsValidationError,
    build_analytics_aggregator,
)
from .analytics_engine import (
    AnalyticsEngine,
    build_analytics_engine,
    deterministic_export_id,
    deterministic_summary_id,
)
from .analytics_telemetry import (
    EVIDENCE_ANALYTICS_EVENT_TYPES,
    emit_evidence_analytics_event,
)
from .analytics_telemetry import (
    emit_completed as emit_analytics_completed,
)
from .analytics_telemetry import (
    emit_failed as emit_analytics_failed,
)
from .analytics_telemetry import (
    emit_latency as emit_analytics_latency,
)
from .analytics_telemetry import (
    emit_requested as emit_analytics_requested,
)
from .assembler import EvidenceAssembler, build_evidence_assembler
from .assigner import (
    ExperimentAssigner,
    assignment_salt,
    build_assignment_rationale,
    build_experiment_assigner,
    deterministic_observation_id,
)
from .collection_telemetry import (
    EVIDENCE_COLLECTION_EVENT_TYPES,
    emit_evidence_collection_event,
)
from .collection_telemetry import (
    emit_completed as emit_collection_completed,
)
from .collection_telemetry import (
    emit_failed as emit_collection_failed,
)
from .collection_telemetry import (
    emit_latency as emit_collection_latency,
)
from .collection_telemetry import (
    emit_requested as emit_collection_requested,
)
from .collector import (
    CollectedObservation,
    EvidenceCollector,
    build_evidence_collector,
)
from .contracts import (
    ANALYTICS_AUDIENCE_ENGINEERING_OPS,
    ANALYTICS_AUDIENCE_GOVERNANCE,
    ANALYTICS_AUDIENCE_RESEARCH,
    ANALYTICS_AUDIENCES,
    ANALYTICS_GRAINS,
    ASSIGNABLE_EXPERIMENT_STATUSES,
    ASSIGNMENT_MECHANISM_HASH,
    ASSIGNMENT_MECHANISM_MANUAL_ALLOWLIST,
    ASSIGNMENT_MECHANISM_OPS_OVERRIDE,
    ASSIGNMENT_MECHANISMS,
    AUTHORITY_EVIDENCE_PLATFORM,
    AUTHORITY_RUNTIME_A,
    AVAILABILITY_AVAILABLE,
    AVAILABILITY_UNAVAILABLE,
    BEHAVIOUR_MISMATCH,
    CLAIM_BOUNDARIES,
    CLAIM_BOUNDARY_LEAKAGE,
    CLAIM_LEARNING_DEPTH,
    CLAIM_LEARNING_SIGNAL,
    CLAIM_ORGANISATION,
    CLAIM_TRANSFER,
    CLAIM_TRUST_INSPECTABILITY,
    CLASS_ADVICE_EVENT,
    CLASS_DELIVERY_EVENT,
    CLASS_FACT_EVENT,
    CLASS_INTERPRETATION_EVENT,
    CLASS_OPS_EVENT,
    CLASS_ORCHESTRATION_EVENT,
    CLASS_RESEARCH_EVENT,
    CONFIDENCE_BANDS,
    EVALUABLE_POLICY_STATUSES,
    EVALUATION_GATE_CODES,
    EVALUATION_KIND_FLAG_MEDIATED_COMPARE,
    EVALUATION_KIND_POST_HOC_INCIDENT,
    EVALUATION_KIND_RESEARCH_LINKAGE,
    EVALUATION_KIND_SHADOW_COMPARE,
    EVALUATION_KIND_SHADOW_DESCRIPTIVE,
    EVALUATION_KINDS,
    EVALUATION_RECOMMENDATIONS,
    EVIDENCE_CLASSES,
    EVIDENCE_ERROR_CODES,
    EVIDENCE_QUALITY_INCOMPLETE,
    EVIDENCE_VERSION_ADVISORY,
    EVIDENCE_VERSION_E0,
    EVIDENCE_VERSION_E1,
    EVIDENCE_VERSION_E2,
    EVIDENCE_VERSION_E3,
    EVIDENCE_VERSION_E4,
    EVIDENCE_VERSION_E5,
    EXPERIMENT_STATUSES,
    EXPOSURE_FLAG_MEDIATED_SERVE,
    EXPOSURE_MODES,
    EXPOSURE_SHADOW_ONLY,
    FORBIDDEN,
    GATE_CODE_CLAIM_BOUNDARY_LEAKAGE,
    GATE_CODE_DEMO_THEATRE,
    GATE_CODE_INCOMPLETE_EXPLAINABILITY,
    GATE_CODE_INSUFFICIENT_OBSERVATIONS,
    GATE_CODE_MISSING_RUNTIME_A,
    GATE_CODE_OVERCLAIM,
    GATE_CODE_STATISTICS_INCOMPLETE,
    GATE_FAILED,
    GATE_INELIGIBLE,
    GATE_PASSED,
    GATE_RESULTS,
    GRAIN_COHORT,
    GRAIN_NIGHT,
    GRAIN_STUDENT,
    GRAIN_SYSTEM,
    INVALID_STATE,
    NOT_FOUND,
    POLICY_OWNER_ADAPTIVE,
    POLICY_OWNER_CROSS_CUTTING,
    POLICY_OWNER_EXPERIENCE_ROUTING,
    POLICY_OWNER_LAYERS,
    POLICY_OWNER_OPS_GATE,
    POLICY_OWNER_STRATEGY,
    POLICY_OWNER_TWIN_PROJECTION,
    POLICY_STATUS_ACTIVE,
    POLICY_STATUS_DEPRECATED,
    POLICY_STATUS_PROPOSED,
    POLICY_STATUS_ROLLED_BACK,
    POLICY_STATUSES,
    QUALITY_FAIL,
    QUALITY_INELIGIBLE,
    QUALITY_PASS,
    QUALITY_RESULTS,
    RECOMMENDATION_EXPAND_SOAK,
    RECOMMENDATION_INCONCLUSIVE,
    RECOMMENDATION_KEEP,
    RECOMMENDATION_REVISE,
    RECOMMENDATION_ROLL_BACK,
    REF_KIND_ADAPTIVE,
    REF_KIND_EXPERIENCE,
    REF_KIND_RUNTIME_A,
    REF_KIND_STRATEGY,
    REF_KIND_TELEMETRY,
    REF_KIND_TWIN,
    REF_KINDS,
    STATISTICAL_DESIGN_DESCRIPTIVE_SOAK,
    STATISTICAL_DESIGN_INTERRUPTED_TIME,
    STATISTICAL_DESIGN_OTHER,
    STATISTICAL_DESIGN_PRE_REGISTERED_COMPARE,
    STATISTICAL_DESIGNS,
    TREND_DIRECTION_DOWN,
    TREND_DIRECTION_FLAT,
    TREND_DIRECTION_NOT_ESTIMABLE,
    TREND_DIRECTION_UP,
    TREND_DIRECTIONS,
    UNAVAILABLE,
    AnalyticsExport,
    AnalyticsSummary,
    ConfidenceSummaryProjection,
    ConsistencySummary,
    EngagementSummary,
    EvidenceAdapter,
    EvidenceAdvisory,
    EvidenceAdvisoryPort,
    EvidenceContext,
    EvidenceFactualSummary,
    EvidenceProjection,
    EvidenceProjectionPort,
    EvidenceProjectionProvenance,
    EvidenceProjectionResult,
    EvidenceQuality,
    EvidenceReadPort,
    EvidenceRecord,
    EvidenceResult,
    ExperimentArm,
    ExperimentDefinition,
    ExperimentObservation,
    ExperimentSummaryProjection,
    FactualConstraint,
    LearningEvidenceContract,
    MetricPoint,
    MetricSeries,
    ObservationRef,
    ObservedEvent,
    ObservedPattern,
    OutcomeMetric,
    PolicyDefinition,
    PolicyEvaluation,
    PolicyEvaluationExplanationBundle,
    PolicyEvaluationExplanationPlaceholder,
    PolicySummaryProjection,
    ScorecardSlice,
    TrendMetadata,
    serialize_canonical,
)
from .evaluation_assembler import (
    EvaluationAssembler,
    build_evaluation_assembler,
)
from .evaluation_explainability import (
    EvaluationExplainability,
    PolicyAssessment,
    build_evaluation_explainability,
)
from .evaluation_factory import (
    PolicyEvaluationFactory,
    build_policy_evaluation_factory,
    deterministic_evaluation_id,
)
from .evaluation_telemetry import (
    EVIDENCE_EVAL_EVENT_TYPES,
    emit_evidence_eval_event,
)
from .evaluation_telemetry import (
    emit_completed as emit_eval_completed,
)
from .evaluation_telemetry import (
    emit_failed as emit_eval_failed,
)
from .evaluation_telemetry import (
    emit_latency as emit_eval_latency,
)
from .evaluation_telemetry import (
    emit_requested as emit_eval_requested,
)
from .evaluation_validator import (
    EvaluationValidationError,
    EvaluationValidator,
    build_evaluation_validator,
)
from .evaluator import PolicyEvaluator, build_policy_evaluator
from .experiment_telemetry import (
    EXPERIMENT_ASSIGNMENT_EVENT_TYPES,
    emit_experiment_assignment_event,
)
from .experiment_telemetry import (
    emit_completed as emit_assignment_completed,
)
from .experiment_telemetry import (
    emit_failed as emit_assignment_failed,
)
from .experiment_telemetry import (
    emit_latency as emit_assignment_latency,
)
from .experiment_telemetry import (
    emit_requested as emit_assignment_requested,
)
from .experiment_validator import (
    ExperimentValidationError,
    ExperimentValidator,
    build_experiment_validator,
    evaluate_eligibility,
)
from .factory import (
    EvidenceFactory,
    build_evidence_factory,
    deterministic_evidence_id,
)
from .factual_query import (
    EVENT_MISSION_STARTED,
    EVENT_REFLECTION_COMPLETED,
    EVENT_SESSION_COMPLETED,
    REPORTING_PERIOD_ALL,
    REPORTING_PERIOD_THIS_WEEK,
    build_factual_summary,
    deterministic_factual_summary_id,
)
from .factual_query import (
    SOURCE_DESCRIPTION as FACTUAL_SOURCE_DESCRIPTION,
)
from .framework import ExperimentFramework, build_experiment_framework
from .policy_registry import (
    PolicyDefinitionRegistry,
    build_policy_definition_registry,
)
from .projector import (
    REASON_ANALYTICS_EMPTY,
    REASON_ANALYTICS_FLAG_OFF,
    REASON_ANALYTICS_INVALID,
    REASON_ANALYTICS_UNAVAILABLE,
    EvidenceGovernanceProjectionPort,
    EvidenceProjector,
    build_evidence_projection_port,
    build_evidence_projector,
    deterministic_projection_id,
)
from .registry import (
    ExperimentDefinitionRegistry,
    build_experiment_definition_registry,
)
from .shadow import (
    EvidencePlatformState,
    EvidenceShadowObservation,
    EvidenceShadowValidator,
    build_evidence_shadow_ops_dashboard,
    build_evidence_shadow_validator,
)
from .shadow_determinism import (
    DRIFT_ANALYTICS_INSTABILITY,
    DRIFT_CLAIM_BOUNDARY_LEAKAGE,
    DRIFT_DETERMINISM_FAILURE,
    DRIFT_EVALUATION_INSTABILITY,
    DRIFT_EVIDENCE_INSTABILITY,
    DRIFT_INPUT_MUTATION,
    DRIFT_KINDS,
    DRIFT_OBSERVATION_INSTABILITY,
    DRIFT_PIPELINE_REPLAY_FAILURE,
    DRIFT_PROJECTION_INSTABILITY,
    DeterminismCheckResult,
    DeterminismValidationResult,
    DeterminismValidator,
    DriftSignal,
    build_determinism_validator,
)
from .shadow_health import (
    OperationalHealthMonitor,
    OperationalHealthSnapshot,
    build_operational_health_monitor,
)
from .shadow_readiness import (
    EVALUATOR_VERSION,
    READINESS_DEGRADED,
    READINESS_NOT_READY,
    READINESS_READY,
    READINESS_STATUSES,
    READINESS_UNAVAILABLE,
    REPORT_VERSION,
    ReadinessEvaluator,
    ReadinessReport,
    ValidationCoverage,
    build_readiness_evaluator,
    deterministic_report_id,
)
from .shadow_rollback import (
    EvidenceShadowRollbackResult,
    RollbackController,
    build_rollback_controller,
    verify_evidence_shadow_rollback,
)
from .shadow_telemetry import (
    EVIDENCE_SHADOW_EVENT_TYPES,
    emit_evidence_shadow_event,
)
from .shadow_telemetry import (
    emit_completed as emit_shadow_completed,
)
from .shadow_telemetry import (
    emit_drift as emit_shadow_drift,
)
from .shadow_telemetry import (
    emit_failed as emit_shadow_failed,
)
from .shadow_telemetry import (
    emit_health as emit_shadow_health,
)
from .shadow_telemetry import (
    emit_latency as emit_shadow_latency,
)
from .shadow_telemetry import (
    emit_readiness as emit_shadow_readiness,
)
from .shadow_telemetry import (
    emit_requested as emit_shadow_requested,
)
from .shadow_telemetry import (
    emit_rollback_verified as emit_shadow_rollback_verified,
)
from .shadow_telemetry import (
    emit_stability as emit_shadow_stability,
)
from .validation import (
    EvidenceValidationError,
    EvidenceValidator,
    build_evidence_validator,
)

__all__ = [
    "ANALYTICS_AUDIENCE_ENGINEERING_OPS",
    "ANALYTICS_AUDIENCE_GOVERNANCE",
    "ANALYTICS_AUDIENCE_RESEARCH",
    "ANALYTICS_AUDIENCES",
    "ANALYTICS_GRAINS",
    "AnalyticsAggregator",
    "AnalyticsEngine",
    "AnalyticsSummary",
    "AnalyticsValidationError",
    "ConfidenceSummaryProjection",
    "EVIDENCE_ANALYTICS_EVENT_TYPES",
    "EVIDENCE_VERSION_E4",
    "EVIDENCE_VERSION_E5",
    "EVIDENCE_VERSION_ADVISORY",
    "EvidenceGovernanceProjectionPort",
    "EvidenceProjection",
    "EvidenceProjectionPort",
    "EvidenceProjectionProvenance",
    "EvidenceProjectionResult",
    "EvidenceProjector",
    "EvidenceAdvisory",
    "EvidenceAdvisoryAssembler",
    "EvidenceAdvisoryPort",
    "ConsistencySummary",
    "EngagementSummary",
    "FactualConstraint",
    "ObservedPattern",
    "ADVISORY_SOURCE_DESCRIPTION",
    "ADVISORY_SOURCE_SERVICE",
    "build_evidence_advisory_assembler",
    "deterministic_advisory_id",
    "format_period_source_description",
    "ExperimentSummaryProjection",
    "GRAIN_COHORT",
    "GRAIN_NIGHT",
    "GRAIN_STUDENT",
    "GRAIN_SYSTEM",
    "MetricPoint",
    "MetricSeries",
    "PolicySummaryProjection",
    "REASON_ANALYTICS_EMPTY",
    "REASON_ANALYTICS_FLAG_OFF",
    "REASON_ANALYTICS_INVALID",
    "REASON_ANALYTICS_UNAVAILABLE",
    "ScorecardSlice",
    "TREND_DIRECTION_DOWN",
    "TREND_DIRECTION_FLAT",
    "TREND_DIRECTION_NOT_ESTIMABLE",
    "TREND_DIRECTION_UP",
    "TREND_DIRECTIONS",
    "TrendMetadata",
    "build_analytics_aggregator",
    "build_analytics_engine",
    "build_evidence_projection_port",
    "build_evidence_projector",
    "deterministic_export_id",
    "deterministic_projection_id",
    "deterministic_summary_id",
    "emit_analytics_completed",
    "emit_analytics_failed",
    "emit_analytics_latency",
    "emit_analytics_requested",
    "emit_evidence_analytics_event",
    "ASSIGNABLE_EXPERIMENT_STATUSES",
    "ASSIGNMENT_MECHANISM_HASH",
    "ASSIGNMENT_MECHANISM_MANUAL_ALLOWLIST",
    "ASSIGNMENT_MECHANISM_OPS_OVERRIDE",
    "ASSIGNMENT_MECHANISMS",
    "AUTHORITY_EVIDENCE_PLATFORM",
    "AUTHORITY_RUNTIME_A",
    "AVAILABILITY_AVAILABLE",
    "AVAILABILITY_UNAVAILABLE",
    "BEHAVIOUR_MISMATCH",
    "CLAIM_BOUNDARIES",
    "CLAIM_BOUNDARY_LEAKAGE",
    "CLAIM_LEARNING_DEPTH",
    "CLAIM_LEARNING_SIGNAL",
    "CLAIM_ORGANISATION",
    "CLAIM_TRANSFER",
    "CLAIM_TRUST_INSPECTABILITY",
    "CLASS_ADVICE_EVENT",
    "CLASS_DELIVERY_EVENT",
    "CLASS_FACT_EVENT",
    "CLASS_INTERPRETATION_EVENT",
    "CLASS_OPS_EVENT",
    "CLASS_ORCHESTRATION_EVENT",
    "CLASS_RESEARCH_EVENT",
    "CONFIDENCE_BANDS",
    "CollectedObservation",
    "EVALUABLE_POLICY_STATUSES",
    "EVALUATION_GATE_CODES",
    "EVALUATION_KIND_FLAG_MEDIATED_COMPARE",
    "EVALUATION_KIND_POST_HOC_INCIDENT",
    "EVALUATION_KIND_RESEARCH_LINKAGE",
    "EVALUATION_KIND_SHADOW_COMPARE",
    "EVALUATION_KIND_SHADOW_DESCRIPTIVE",
    "EVALUATION_KINDS",
    "EVALUATION_RECOMMENDATIONS",
    "EVIDENCE_CLASSES",
    "EVIDENCE_COLLECTION_EVENT_TYPES",
    "EVIDENCE_ERROR_CODES",
    "EVIDENCE_EVAL_EVENT_TYPES",
    "EVIDENCE_QUALITY_INCOMPLETE",
    "EVIDENCE_VERSION_E0",
    "EVIDENCE_VERSION_E1",
    "EVIDENCE_VERSION_E2",
    "EVIDENCE_VERSION_E3",
    "EXPERIMENT_ASSIGNMENT_EVENT_TYPES",
    "EXPERIMENT_STATUSES",
    "EXPOSURE_FLAG_MEDIATED_SERVE",
    "EXPOSURE_MODES",
    "EXPOSURE_SHADOW_ONLY",
    "EvaluationAssembler",
    "EvaluationExplainability",
    "EvaluationValidationError",
    "EvaluationValidator",
    "EvidenceAssembler",
    "EvidenceAdapter",
    "EvidenceCollector",
    "EvidenceContext",
    "EvidenceFactory",
    "EvidenceFactualSummary",
    "EvidencePlatformAdapter",
    "EvidenceQuality",
    "EvidenceReadPort",
    "EvidenceRecord",
    "EvidenceResult",
    "EvidenceValidationError",
    "EvidenceValidator",
    "EVENT_MISSION_STARTED",
    "EVENT_REFLECTION_COMPLETED",
    "EVENT_SESSION_COMPLETED",
    "FACTUAL_SOURCE_DESCRIPTION",
    "REPORTING_PERIOD_ALL",
    "REPORTING_PERIOD_THIS_WEEK",
    "build_factual_summary",
    "deterministic_factual_summary_id",
    "ExperimentArm",
    "ExperimentAssigner",
    "ExperimentDefinition",
    "ExperimentDefinitionRegistry",
    "ExperimentFramework",
    "ExperimentObservation",
    "ExperimentValidationError",
    "ExperimentValidator",
    "FORBIDDEN",
    "GATE_CODE_CLAIM_BOUNDARY_LEAKAGE",
    "GATE_CODE_DEMO_THEATRE",
    "GATE_CODE_INCOMPLETE_EXPLAINABILITY",
    "GATE_CODE_INSUFFICIENT_OBSERVATIONS",
    "GATE_CODE_MISSING_RUNTIME_A",
    "GATE_CODE_OVERCLAIM",
    "GATE_CODE_STATISTICS_INCOMPLETE",
    "GATE_FAILED",
    "GATE_INELIGIBLE",
    "GATE_PASSED",
    "GATE_RESULTS",
    "INVALID_STATE",
    "LearningEvidenceContract",
    "NOT_FOUND",
    "ObservationRef",
    "ObservedEvent",
    "OutcomeMetric",
    "POLICY_OWNER_ADAPTIVE",
    "POLICY_OWNER_CROSS_CUTTING",
    "POLICY_OWNER_EXPERIENCE_ROUTING",
    "POLICY_OWNER_LAYERS",
    "POLICY_OWNER_OPS_GATE",
    "POLICY_OWNER_STRATEGY",
    "POLICY_OWNER_TWIN_PROJECTION",
    "POLICY_STATUS_ACTIVE",
    "POLICY_STATUS_DEPRECATED",
    "POLICY_STATUS_PROPOSED",
    "POLICY_STATUS_ROLLED_BACK",
    "POLICY_STATUSES",
    "PolicyAssessment",
    "PolicyDefinition",
    "PolicyDefinitionRegistry",
    "PolicyEvaluation",
    "PolicyEvaluationExplanationBundle",
    "PolicyEvaluationExplanationPlaceholder",
    "PolicyEvaluationFactory",
    "PolicyEvaluator",
    "QUALITY_FAIL",
    "QUALITY_INELIGIBLE",
    "QUALITY_PASS",
    "QUALITY_RESULTS",
    "RECOMMENDATION_EXPAND_SOAK",
    "RECOMMENDATION_INCONCLUSIVE",
    "RECOMMENDATION_KEEP",
    "RECOMMENDATION_REVISE",
    "RECOMMENDATION_ROLL_BACK",
    "REF_KIND_ADAPTIVE",
    "REF_KIND_EXPERIENCE",
    "REF_KIND_RUNTIME_A",
    "REF_KIND_STRATEGY",
    "REF_KIND_TELEMETRY",
    "REF_KIND_TWIN",
    "REF_KINDS",
    "STATISTICAL_DESIGN_DESCRIPTIVE_SOAK",
    "STATISTICAL_DESIGN_INTERRUPTED_TIME",
    "STATISTICAL_DESIGN_OTHER",
    "STATISTICAL_DESIGN_PRE_REGISTERED_COMPARE",
    "STATISTICAL_DESIGNS",
    "UNAVAILABLE",
    "AnalyticsExport",
    "assignment_salt",
    "build_assignment_rationale",
    "build_evaluation_assembler",
    "build_evaluation_explainability",
    "build_evaluation_validator",
    "build_evidence_assembler",
    "build_evidence_collector",
    "build_evidence_factory",
    "build_evidence_platform_adapter",
    "build_evidence_validator",
    "build_experiment_assigner",
    "build_experiment_definition_registry",
    "build_experiment_framework",
    "build_experiment_validator",
    "build_policy_definition_registry",
    "build_policy_evaluation_factory",
    "build_policy_evaluator",
    "deterministic_evaluation_id",
    "deterministic_evidence_id",
    "deterministic_observation_id",
    "emit_assignment_completed",
    "emit_assignment_failed",
    "emit_assignment_latency",
    "emit_assignment_requested",
    "emit_collection_completed",
    "emit_collection_failed",
    "emit_collection_latency",
    "emit_collection_requested",
    "emit_eval_completed",
    "emit_eval_failed",
    "emit_eval_latency",
    "emit_eval_requested",
    "emit_evidence_collection_event",
    "emit_evidence_eval_event",
    "emit_experiment_assignment_event",
    "empty_evidence_record",
    "evaluate_eligibility",
    "serialize_canonical",
    # E5 Shadow Validation & Operational Readiness
    "DRIFT_ANALYTICS_INSTABILITY",
    "DRIFT_CLAIM_BOUNDARY_LEAKAGE",
    "DRIFT_DETERMINISM_FAILURE",
    "DRIFT_EVALUATION_INSTABILITY",
    "DRIFT_EVIDENCE_INSTABILITY",
    "DRIFT_INPUT_MUTATION",
    "DRIFT_KINDS",
    "DRIFT_OBSERVATION_INSTABILITY",
    "DRIFT_PIPELINE_REPLAY_FAILURE",
    "DRIFT_PROJECTION_INSTABILITY",
    "DeterminismCheckResult",
    "DeterminismValidationResult",
    "DeterminismValidator",
    "DriftSignal",
    "EVALUATOR_VERSION",
    "EVIDENCE_SHADOW_EVENT_TYPES",
    "EvidencePlatformState",
    "EvidenceShadowObservation",
    "EvidenceShadowRollbackResult",
    "EvidenceShadowValidator",
    "OperationalHealthMonitor",
    "OperationalHealthSnapshot",
    "READINESS_DEGRADED",
    "READINESS_NOT_READY",
    "READINESS_READY",
    "READINESS_STATUSES",
    "READINESS_UNAVAILABLE",
    "REPORT_VERSION",
    "ReadinessEvaluator",
    "ReadinessReport",
    "RollbackController",
    "ValidationCoverage",
    "build_determinism_validator",
    "build_evidence_shadow_ops_dashboard",
    "build_evidence_shadow_validator",
    "build_operational_health_monitor",
    "build_readiness_evaluator",
    "build_rollback_controller",
    "deterministic_report_id",
    "emit_evidence_shadow_event",
    "emit_shadow_completed",
    "emit_shadow_drift",
    "emit_shadow_failed",
    "emit_shadow_health",
    "emit_shadow_latency",
    "emit_shadow_readiness",
    "emit_shadow_requested",
    "emit_shadow_rollback_verified",
    "emit_shadow_stability",
    "verify_evidence_shadow_rollback",
]
