"""Educational recommendations — decisions generated by reasoning."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime
from enum import StrEnum


class RecommendationPriority(StrEnum):
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


@dataclass(frozen=True)
class Recommendation:
    """Explainable educational decision produced by StudentReasoningService."""

    recommendation_id: str
    twin_id: str
    title: str
    reason: str
    priority: RecommendationPriority = RecommendationPriority.MEDIUM
    confidence: float = 0.0
    curriculum_entity_id: str = ""
    supporting_evidence: tuple[str, ...] = ()
    related_gap_id: str | None = None
    created_at: datetime | None = None
    status: str = "active"

    def __post_init__(self) -> None:
        if not (self.recommendation_id or "").strip():
            raise ValueError("recommendation_id is required")
        if not (self.title or "").strip():
            raise ValueError("recommendation title is required")
        object.__setattr__(self, "confidence", _clamp(self.confidence))
        priority = (
            self.priority
            if isinstance(self.priority, RecommendationPriority)
            else RecommendationPriority(str(self.priority))
        )
        object.__setattr__(self, "priority", priority)
        when = self.created_at
        if when is not None and when.tzinfo is not None:
            object.__setattr__(
                self, "created_at", when.astimezone(UTC).replace(tzinfo=None)
            )
        object.__setattr__(
            self, "supporting_evidence", tuple(self.supporting_evidence or ())
        )


def _clamp(value: float) -> float:
    return max(0.0, min(1.0, float(value)))
