"""add_decision_model

Revision ID: 0a272936a47b
Revises: 202607080005
Create Date: 2026-07-08 19:50:33.827344
"""

from alembic import op
import sqlalchemy as sa


revision = '0a272936a47b'
down_revision = '202607080005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_title', sa.String(length=255), nullable=False),
    sa.Column('recommendation_category', sa.String(length=100), nullable=False),
    sa.Column('recommendation_priority', sa.String(length=50), nullable=False),
    sa.Column('recommendation_reason', sa.Text(), nullable=False),
    sa.Column('recommendation_expected_benefit', sa.Text(), nullable=False),
    sa.Column('recommendation_generated_at', sa.DateTime(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('outcome_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.alter_column('colour',
               existing_type=sa.VARCHAR(length=7),
               nullable=True,
               existing_server_default=sa.text("'#007bff'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.alter_column('colour',
               existing_type=sa.VARCHAR(length=7),
               nullable=False,
               existing_server_default=sa.text("'#007bff'"))

    op.drop_table('decisions')
    # ### end Alembic commands ###
