"""Controlled Educational Effectiveness Trial package (P4-MS001).

Operational trial framework comparing baseline recommendations with
policy-weighted recommendations under controlled rollout.

Feature flag ``KWALITEC_EDUCATIONAL_TRIALS`` / ``ENABLE_EDUCATIONAL_TRIALS``
defaults OFF.

Does not expand advisory fields. Does not infer mastery. Does not modify
Adaptive / Recovery / Strategy. Runtime A remains sole educational authority.
"""

from __future__ import annotations

from .cohort import (
    ASSIGNER_ID,
    ASSIGNER_VERSION,
    assign_cohort,
    opaque_student_key,
    student_bucket,
    student_in_treatment,
)
from .contracts import (
    APPROVED_ADVISORY_FIELD,
    APPROVED_ADVISORY_FIELDS,
    AUTHORITY_EDUCATIONAL_TRIAL,
    AUTHORITY_POLICY_WEIGHTING,
    AUTHORITY_RUNTIME_A,
    COHORT_BASELINE,
    COHORT_TREATMENT,
    COHORT_UNASSIGNED,
    DEFAULT_POLICY_VERSION,
    DEFAULT_ROLLOUT_SALT,
    DEFAULT_SUCCESS_METRICS,
    DEFAULT_TRIAL_ID,
    EDUCATIONAL_TRIAL_VERSION,
    INVALID_STATE,
    METRIC_MISSION_COMPLETION,
    METRIC_POLICY_ACTIVATION,
    METRIC_RECOMMENDATION_ACCEPTANCE,
    METRIC_REFLECTION_COMPLETION,
    METRIC_STUDY_SESSION_COMPLETION,
    OPERATIONAL_SUCCESS_METRICS,
    TRIAL_COHORTS,
    TRIAL_ERROR_CODES,
    TRIAL_STATUS_ACTIVE,
    TRIAL_STATUS_CANCELLED,
    TRIAL_STATUS_COMPLETED,
    TRIAL_STATUS_DRAFT,
    TRIAL_STATUS_PAUSED,
    TRIAL_STATUSES,
    UNAVAILABLE,
    ActivationStatistics,
    CohortAssignment,
    CohortStatistics,
    EducationalTrial,
    EducationalTrialResult,
    TrialMetricObservation,
    TrialMetrics,
    TrialSummary,
    serialize_canonical,
    snapshot_mapping,
    validate_educational_trial,
)
from .service import (
    DEFAULT_OBSERVATION_WINDOW,
    SERVICE_ID,
    SOURCE_SERVICE,
    EducationalTrialService,
    build_educational_trial_service,
    deterministic_observation_id,
    deterministic_summary_id,
    resolve_default_trial,
)

__all__ = [
    "APPROVED_ADVISORY_FIELD",
    "APPROVED_ADVISORY_FIELDS",
    "ASSIGNER_ID",
    "ASSIGNER_VERSION",
    "AUTHORITY_EDUCATIONAL_TRIAL",
    "AUTHORITY_POLICY_WEIGHTING",
    "AUTHORITY_RUNTIME_A",
    "COHORT_BASELINE",
    "COHORT_TREATMENT",
    "COHORT_UNASSIGNED",
    "DEFAULT_OBSERVATION_WINDOW",
    "DEFAULT_POLICY_VERSION",
    "DEFAULT_ROLLOUT_SALT",
    "DEFAULT_SUCCESS_METRICS",
    "DEFAULT_TRIAL_ID",
    "EDUCATIONAL_TRIAL_VERSION",
    "INVALID_STATE",
    "METRIC_MISSION_COMPLETION",
    "METRIC_POLICY_ACTIVATION",
    "METRIC_RECOMMENDATION_ACCEPTANCE",
    "METRIC_REFLECTION_COMPLETION",
    "METRIC_STUDY_SESSION_COMPLETION",
    "OPERATIONAL_SUCCESS_METRICS",
    "SERVICE_ID",
    "SOURCE_SERVICE",
    "TRIAL_COHORTS",
    "TRIAL_ERROR_CODES",
    "TRIAL_STATUSES",
    "TRIAL_STATUS_ACTIVE",
    "TRIAL_STATUS_CANCELLED",
    "TRIAL_STATUS_COMPLETED",
    "TRIAL_STATUS_DRAFT",
    "TRIAL_STATUS_PAUSED",
    "UNAVAILABLE",
    "ActivationStatistics",
    "CohortAssignment",
    "CohortStatistics",
    "EducationalTrial",
    "EducationalTrialResult",
    "EducationalTrialService",
    "TrialMetricObservation",
    "TrialMetrics",
    "TrialSummary",
    "assign_cohort",
    "build_educational_trial_service",
    "deterministic_observation_id",
    "deterministic_summary_id",
    "opaque_student_key",
    "resolve_default_trial",
    "serialize_canonical",
    "snapshot_mapping",
    "student_bucket",
    "student_in_treatment",
    "validate_educational_trial",
]
