"""Adaptive Engine Adapter package (MS-003 A0–A6; MS-004 T4 Twin input).

Contracts, DTOs, Adaptive Input Assembler, AdaptiveEngineExecutor,
shadow orchestrator, Explainability Gate, Experience AdaptiveDecisionPort
cutover router, Observational Traceability, Shadow Soak monitors, and
optional TwinInputAdapter (read-only TwinSnapshot consumption).
Adaptive authority defaults OFF — RecommendationService remains primary
unless Engine + Shadow + Authority flags enable eligible cutover. Runtime A
educational writes are forbidden. Twin consumption never synthesises,
mutates, or persists Twin data. Traceability and Shadow Soak are
observational only (in-memory / telemetry; no educational persistence; no
student-facing history; soak never influences the student).
"""

from __future__ import annotations

from .adapter import (
    AdaptiveEngineAdapter,
    build_adaptive_engine_adapter,
    empty_adaptive_output,
)
from .assembler import AdaptiveInputAssembler, build_adaptive_input_assembler
from .collectors import (
    CollectorResult,
    CurriculumCollector,
    EvidenceCollector,
    LifecycleStageCollector,
    MissionCollector,
    ReadinessCollector,
    RuntimeACollector,
    StudentGoalsCollector,
    StudyAttemptCollector,
    TopicProgressCollector,
    build_default_collectors,
)
from .contracts import (
    ADAPTIVE_ERROR_CODES,
    AUTHORITY_ADAPTIVE_ENGINE,
    AUTHORITY_RUNTIME_A,
    BEHAVIOUR_MISMATCH,
    CONFIDENCE_BANDS,
    EXPLAINABILITY_INCOMPLETE,
    FORBIDDEN,
    INVALID_STATE,
    NO_ACTIVE_PLAN,
    NOT_FOUND,
    UNAVAILABLE,
    AdaptiveDecisionContract,
    AdaptiveDecisionResult,
    AdaptiveEngineBridge,
    AdaptiveInputBundle,
    AdaptiveOutputBundle,
    ConfidencePlaceholder,
    EvidenceRef,
    ExplanationBundle,
    RecommendationPlaceholder,
    RuleRef,
    TopicRef,
    TwinAdaptiveInputAttachment,
    serialize_canonical,
)
from .executor import (
    AdaptiveEngineExecutor,
    build_adaptive_engine_executor,
)
from .gate import (
    ExplainabilityGate,
    ExplainabilityGateResult,
    build_explainability_gate,
)
from .port_cutover import (
    AdaptiveExperiencePortRouter,
    adaptive_experience_cutover_active,
    build_adaptive_experience_port_router,
    map_adaptive_output_to_recommendation,
)
from .provenance import (
    AVAILABILITY_AVAILABLE,
    AVAILABILITY_UNAVAILABLE,
    FIELD_CURRICULUM,
    FIELD_EVIDENCE,
    FIELD_LIFECYCLE_STAGE,
    FIELD_MISSION,
    FIELD_READINESS,
    FIELD_STUDENT_GOALS,
    FIELD_STUDY_ATTEMPTS,
    FIELD_TOPIC_PROGRESS,
    FIELD_TWIN,
    INPUT_FIELD_NAMES,
    OPTIONAL_INPUT_FIELD_NAMES,
    REASON_COLLECTOR_ERROR,
    REASON_INVALID_STUDENT_ID,
    REASON_NO_ACTIVE_PLAN,
    REASON_NO_CURRICULUM,
    REASON_NOT_FOUND,
    REASON_UNAVAILABLE,
    FieldProvenance,
    available_provenance,
    unavailable_provenance,
)
from .quality_rules import (
    GATE_RULE_IDS,
    QualityViolation,
    evaluate_quality_rules,
    validate_explanation_bundle,
)
from .shadow import (
    AdaptiveShadowOrchestrator,
    build_adaptive_shadow_orchestrator,
    explanation_is_complete,
)
from .soak import (
    ShadowSoakOrchestrator,
    SoakObservation,
    build_shadow_soak_orchestrator,
    build_soak_ops_dashboard,
)
from .soak_health import (
    SoakHealthMetrics,
    SoakHealthSnapshot,
    build_soak_health_metrics,
)
from .soak_monitors import (
    DRIFT_DETERMINISM_FAILURE,
    DRIFT_KINDS,
    DRIFT_MISSING_EXPLANATION,
    DRIFT_TRACE_FAILURE,
    DRIFT_UNEXPECTED_RECOMMENDATION_CHANGE,
    DRIFT_UNEXPLAINED_DIVERGENCE,
    DeterminismMonitor,
    DeterminismReplayResult,
    DriftDetectionMonitor,
    DriftSignal,
    RecommendationComparison,
    RecommendationComparisonMonitor,
)
from .soak_rollback import (
    RollbackVerificationResult,
    RollbackVerifier,
    build_rollback_verifier,
    verify_adaptive_rollback,
)
from .traceability import (
    AUTHORITY_ADAPTIVE_DELIVERED,
    AUTHORITY_FAILED,
    AUTHORITY_GATE_INELIGIBLE,
    AUTHORITY_INACTIVE,
    AUTHORITY_RECOMMENDATION_FALLBACK,
    AUTHORITY_SHADOW_ONLY,
    DELIVERY_DELIVERED,
    DELIVERY_NONE,
    DELIVERY_SHADOW_ONLY,
    LINEAGE_STAGES,
    ROUTING_AUTHORITATIVE,
    ROUTING_FAILED,
    ROUTING_FALLBACK,
    ROUTING_INACTIVE,
    ROUTING_SHADOW_ONLY,
    DecisionLineage,
    DecisionTrace,
    FeatureFlagSnapshot,
    TraceabilityService,
    build_decision_lineage,
    build_traceability_service,
    input_bundle_ref,
    new_correlation_id,
    output_bundle_ref,
    resolve_correlation_id,
    runtime_a_snapshot_id,
)
from .twin_input import (
    REASON_TWIN_FLAG_OFF,
    REASON_TWIN_INVALID,
    REASON_TWIN_UNAVAILABLE,
    TwinInputAdapter,
    build_twin_input_adapter,
    twin_attachment_is_available,
)
from .validation import AdaptiveInputValidationError

__all__ = [
    "ADAPTIVE_ERROR_CODES",
    "AUTHORITY_ADAPTIVE_DELIVERED",
    "AUTHORITY_ADAPTIVE_ENGINE",
    "AUTHORITY_FAILED",
    "AUTHORITY_GATE_INELIGIBLE",
    "AUTHORITY_INACTIVE",
    "AUTHORITY_RECOMMENDATION_FALLBACK",
    "AUTHORITY_RUNTIME_A",
    "AUTHORITY_SHADOW_ONLY",
    "AVAILABILITY_AVAILABLE",
    "AVAILABILITY_UNAVAILABLE",
    "BEHAVIOUR_MISMATCH",
    "CONFIDENCE_BANDS",
    "DELIVERY_DELIVERED",
    "DELIVERY_NONE",
    "DELIVERY_SHADOW_ONLY",
    "DRIFT_DETERMINISM_FAILURE",
    "DRIFT_KINDS",
    "DRIFT_MISSING_EXPLANATION",
    "DRIFT_TRACE_FAILURE",
    "DRIFT_UNEXPECTED_RECOMMENDATION_CHANGE",
    "DRIFT_UNEXPLAINED_DIVERGENCE",
    "EXPLAINABILITY_INCOMPLETE",
    "FIELD_CURRICULUM",
    "FIELD_EVIDENCE",
    "FIELD_LIFECYCLE_STAGE",
    "FIELD_MISSION",
    "FIELD_READINESS",
    "FIELD_STUDENT_GOALS",
    "FIELD_STUDY_ATTEMPTS",
    "FIELD_TOPIC_PROGRESS",
    "FIELD_TWIN",
    "FORBIDDEN",
    "GATE_RULE_IDS",
    "INPUT_FIELD_NAMES",
    "INVALID_STATE",
    "LINEAGE_STAGES",
    "NO_ACTIVE_PLAN",
    "NOT_FOUND",
    "OPTIONAL_INPUT_FIELD_NAMES",
    "REASON_COLLECTOR_ERROR",
    "REASON_INVALID_STUDENT_ID",
    "REASON_NO_ACTIVE_PLAN",
    "REASON_NO_CURRICULUM",
    "REASON_NOT_FOUND",
    "REASON_TWIN_FLAG_OFF",
    "REASON_TWIN_INVALID",
    "REASON_TWIN_UNAVAILABLE",
    "REASON_UNAVAILABLE",
    "ROUTING_AUTHORITATIVE",
    "ROUTING_FAILED",
    "ROUTING_FALLBACK",
    "ROUTING_INACTIVE",
    "ROUTING_SHADOW_ONLY",
    "UNAVAILABLE",
    "AdaptiveDecisionContract",
    "AdaptiveDecisionResult",
    "AdaptiveEngineAdapter",
    "AdaptiveEngineBridge",
    "AdaptiveEngineExecutor",
    "AdaptiveExperiencePortRouter",
    "AdaptiveInputAssembler",
    "AdaptiveInputBundle",
    "AdaptiveInputValidationError",
    "AdaptiveOutputBundle",
    "AdaptiveShadowOrchestrator",
    "CollectorResult",
    "ConfidencePlaceholder",
    "CurriculumCollector",
    "DecisionLineage",
    "DecisionTrace",
    "DeterminismMonitor",
    "DeterminismReplayResult",
    "DriftDetectionMonitor",
    "DriftSignal",
    "EvidenceCollector",
    "EvidenceRef",
    "ExplainabilityGate",
    "ExplainabilityGateResult",
    "ExplanationBundle",
    "FeatureFlagSnapshot",
    "FieldProvenance",
    "LifecycleStageCollector",
    "MissionCollector",
    "QualityViolation",
    "ReadinessCollector",
    "RecommendationComparison",
    "RecommendationComparisonMonitor",
    "RecommendationPlaceholder",
    "RollbackVerificationResult",
    "RollbackVerifier",
    "RuleRef",
    "RuntimeACollector",
    "ShadowSoakOrchestrator",
    "SoakHealthMetrics",
    "SoakHealthSnapshot",
    "SoakObservation",
    "StudentGoalsCollector",
    "StudyAttemptCollector",
    "TopicProgressCollector",
    "TopicRef",
    "TraceabilityService",
    "TwinAdaptiveInputAttachment",
    "TwinInputAdapter",
    "adaptive_experience_cutover_active",
    "available_provenance",
    "build_adaptive_engine_adapter",
    "build_adaptive_engine_executor",
    "build_adaptive_experience_port_router",
    "build_adaptive_input_assembler",
    "build_adaptive_shadow_orchestrator",
    "build_decision_lineage",
    "build_default_collectors",
    "build_explainability_gate",
    "build_rollback_verifier",
    "build_shadow_soak_orchestrator",
    "build_soak_health_metrics",
    "build_soak_ops_dashboard",
    "build_traceability_service",
    "build_twin_input_adapter",
    "empty_adaptive_output",
    "evaluate_quality_rules",
    "explanation_is_complete",
    "input_bundle_ref",
    "map_adaptive_output_to_recommendation",
    "new_correlation_id",
    "output_bundle_ref",
    "resolve_correlation_id",
    "runtime_a_snapshot_id",
    "serialize_canonical",
    "twin_attachment_is_available",
    "unavailable_provenance",
    "validate_explanation_bundle",
    "verify_adaptive_rollback",
]
