"""Student Experience — application-layer presentation composition.

Composes Education OS outputs into student-facing view models.
Never performs educational reasoning.
"""

from __future__ import annotations

from application.student_experience.coach import (
    CelebrationMoment,
    CelebrationMoments,
    CoachContext,
    CoachContextPublisher,
    CoachInputs,
    CoachPublisher,
    CoachSnapshot,
    ConversationContext,
    ExplanationCard,
    ExplanationCards,
    LearningCoachService,
    ReflectionPrompt,
    ReflectionPrompts,
    SuggestedQuestion,
    SuggestedQuestions,
)
from application.student_experience.home import (
    AchievementCard,
    AchievementProvider,
    ExamReadinessCard,
    HomePublisher,
    HomeSnapshot,
    HomeViewModel,
    LearningInsightCard,
    MomentumCard,
    NotificationProvider,
    ProgressCard,
    QuickActionsCard,
    StudentHomeService,
    TodaysFocusCard,
    TodaysStudySessionCard,
    UpcomingMilestoneCard,
)
from application.student_experience.integration import (
    CascadeStep,
    ExperienceBundleId,
    ExperienceIntegrationPublisher,
    ExperienceIntegrationService,
    ExperienceJourneyViewModel,
    ExperienceSnapshotBundle,
    IntegratedNextAction,
    IntegrationInputs,
    IntegrationTrigger,
    JourneySurface,
    ReadinessChangeNotice,
    SurfaceState,
)
from application.student_experience.progress import (
    ConsistencyCard,
    GrowthCard,
    JourneyExportProvider,
    JourneyPublisher,
    JourneySnapshot,
    LearningJourneyService,
    LearningJourneyViewModel,
    MilestoneProvider,
    ProgressOverviewCard,
    StudyHabitsCard,
    TimelineCard,
)
from application.student_experience.readiness import (
    ActionPlanCard,
    ConfidenceCard,
    EvidenceQualityCard,
    ExamReadinessService,
    ExamReadinessViewModel,
    ReadinessCard,
    ReadinessExportProvider,
    ReadinessPublisher,
    ReadinessSnapshot,
    ReadinessTrendCard,
    RiskCard,
    StrengthCard,
)
from application.student_experience.workspace import (
    CompletionCard,
    CurrentSessionCard,
    FocusCard,
    MissionCard,
    ObjectivesCard,
    ReflectionCard,
    ResourcesCard,
    SessionTimerCard,
    StudyWorkspaceService,
    StudyWorkspaceViewModel,
    WorkspacePublisher,
    WorkspaceResourceProvider,
    WorkspaceSnapshot,
)
from application.student_experience.workspace import (
    ProgressCard as WorkspaceProgressCard,
)

__all__ = [
    # Home (XP-001)
    "AchievementCard",
    "AchievementProvider",
    "ExamReadinessCard",
    "HomePublisher",
    "HomeSnapshot",
    "HomeViewModel",
    "LearningInsightCard",
    "MomentumCard",
    "NotificationProvider",
    "ProgressCard",
    "QuickActionsCard",
    "StudentHomeService",
    "TodaysFocusCard",
    "TodaysStudySessionCard",
    "UpcomingMilestoneCard",
    # Progress / Learning Journey (XP-002)
    "ConsistencyCard",
    "GrowthCard",
    "JourneyExportProvider",
    "JourneyPublisher",
    "JourneySnapshot",
    "LearningJourneyService",
    "LearningJourneyViewModel",
    "MilestoneProvider",
    "ProgressOverviewCard",
    "StudyHabitsCard",
    "TimelineCard",
    # Exam Readiness (XP-003)
    "ActionPlanCard",
    "ConfidenceCard",
    "EvidenceQualityCard",
    "ExamReadinessService",
    "ExamReadinessViewModel",
    "ReadinessCard",
    "ReadinessExportProvider",
    "ReadinessPublisher",
    "ReadinessSnapshot",
    "ReadinessTrendCard",
    "RiskCard",
    "StrengthCard",
    # Adaptive Study Workspace (XP-004)
    "CompletionCard",
    "CurrentSessionCard",
    "FocusCard",
    "MissionCard",
    "ObjectivesCard",
    "ReflectionCard",
    "ResourcesCard",
    "SessionTimerCard",
    "StudyWorkspaceService",
    "StudyWorkspaceViewModel",
    "WorkspaceProgressCard",
    "WorkspacePublisher",
    "WorkspaceResourceProvider",
    "WorkspaceSnapshot",
    # AI Learning Coach (XP-005)
    "CelebrationMoment",
    "CelebrationMoments",
    "CoachContext",
    "CoachContextPublisher",
    "CoachInputs",
    "CoachPublisher",
    "CoachSnapshot",
    "ConversationContext",
    "ExplanationCard",
    "ExplanationCards",
    "LearningCoachService",
    "ReflectionPrompt",
    "ReflectionPrompts",
    "SuggestedQuestion",
    "SuggestedQuestions",
    # Experience Integration (PX-002)
    "CascadeStep",
    "ExperienceBundleId",
    "ExperienceIntegrationPublisher",
    "ExperienceIntegrationService",
    "ExperienceJourneyViewModel",
    "ExperienceSnapshotBundle",
    "IntegratedNextAction",
    "IntegrationInputs",
    "IntegrationTrigger",
    "JourneySurface",
    "ReadinessChangeNotice",
    "SurfaceState",
]
