"""Named Version 2 integration event types."""

from __future__ import annotations

from app.infrastructure.events.base import IntegrationEvent
from app.infrastructure.events.types.experience import EXPERIENCE_EVENT_TYPES

EVIDENCE_RECORDED = "EvidenceRecorded"
TWIN_UPDATED = "TwinUpdated"
ADAPTIVE_DECISION_GENERATED = "AdaptiveDecisionGenerated"
MISSION_UPDATED = "MissionUpdated"
CURRICULUM_PUBLISHED = "CurriculumPublished"
CURRICULUM_VALIDATED = "CurriculumValidated"
LEARNING_SESSION_COMPLETED = "LearningSessionCompleted"

# Mission Read Bridge observational events (MS-001 Directive 003).
# Defined here (not imported from the adapter package) to avoid import cycles.
MISSION_BRIDGE_REQUESTED = "MISSION_BRIDGE_REQUESTED"
MISSION_BRIDGE_SUCCESS = "MISSION_BRIDGE_SUCCESS"
MISSION_BRIDGE_FAILURE = "MISSION_BRIDGE_FAILURE"
MISSION_BRIDGE_LATENCY = "MISSION_BRIDGE_LATENCY"
MISSION_BRIDGE_EVENT_TYPES: tuple[str, ...] = (
    MISSION_BRIDGE_REQUESTED,
    MISSION_BRIDGE_SUCCESS,
    MISSION_BRIDGE_FAILURE,
    MISSION_BRIDGE_LATENCY,
)

# Mission Start Bridge observational events (MS-001 Directive 004).
MISSION_START_BRIDGE_REQUESTED = "MISSION_START_BRIDGE_REQUESTED"
MISSION_START_BRIDGE_SUCCESS = "MISSION_START_BRIDGE_SUCCESS"
MISSION_START_BRIDGE_FAILURE = "MISSION_START_BRIDGE_FAILURE"
MISSION_START_BRIDGE_LATENCY = "MISSION_START_BRIDGE_LATENCY"
MISSION_START_BRIDGE_EVENT_TYPES: tuple[str, ...] = (
    MISSION_START_BRIDGE_REQUESTED,
    MISSION_START_BRIDGE_SUCCESS,
    MISSION_START_BRIDGE_FAILURE,
    MISSION_START_BRIDGE_LATENCY,
)

# Mission Resume Bridge observational events (MS-001 Directive 005).
MISSION_RESUME_BRIDGE_REQUESTED = "MISSION_RESUME_BRIDGE_REQUESTED"
MISSION_RESUME_BRIDGE_SUCCESS = "MISSION_RESUME_BRIDGE_SUCCESS"
MISSION_RESUME_BRIDGE_FAILURE = "MISSION_RESUME_BRIDGE_FAILURE"
MISSION_RESUME_BRIDGE_LATENCY = "MISSION_RESUME_BRIDGE_LATENCY"
MISSION_RESUME_BRIDGE_EVENT_TYPES: tuple[str, ...] = (
    MISSION_RESUME_BRIDGE_REQUESTED,
    MISSION_RESUME_BRIDGE_SUCCESS,
    MISSION_RESUME_BRIDGE_FAILURE,
    MISSION_RESUME_BRIDGE_LATENCY,
)

# Session Completion Bridge observational events (MS-001 Directive 006).
SESSION_COMPLETION_BRIDGE_REQUESTED = "SESSION_COMPLETION_BRIDGE_REQUESTED"
SESSION_COMPLETION_BRIDGE_SUCCESS = "SESSION_COMPLETION_BRIDGE_SUCCESS"
SESSION_COMPLETION_BRIDGE_FAILURE = "SESSION_COMPLETION_BRIDGE_FAILURE"
SESSION_COMPLETION_BRIDGE_LATENCY = "SESSION_COMPLETION_BRIDGE_LATENCY"
SESSION_COMPLETION_BRIDGE_EVENT_TYPES: tuple[str, ...] = (
    SESSION_COMPLETION_BRIDGE_REQUESTED,
    SESSION_COMPLETION_BRIDGE_SUCCESS,
    SESSION_COMPLETION_BRIDGE_FAILURE,
    SESSION_COMPLETION_BRIDGE_LATENCY,
)

# Recommendation Read Bridge observational events (MS-001 Directive 007).
RECOMMENDATION_BRIDGE_REQUESTED = "RECOMMENDATION_BRIDGE_REQUESTED"
RECOMMENDATION_BRIDGE_SUCCESS = "RECOMMENDATION_BRIDGE_SUCCESS"
RECOMMENDATION_BRIDGE_FAILURE = "RECOMMENDATION_BRIDGE_FAILURE"
RECOMMENDATION_BRIDGE_LATENCY = "RECOMMENDATION_BRIDGE_LATENCY"
RECOMMENDATION_BRIDGE_EVENT_TYPES: tuple[str, ...] = (
    RECOMMENDATION_BRIDGE_REQUESTED,
    RECOMMENDATION_BRIDGE_SUCCESS,
    RECOMMENDATION_BRIDGE_FAILURE,
    RECOMMENDATION_BRIDGE_LATENCY,
)

# Journey Read Bridge observational events (MS-002 Directive 002).
JOURNEY_BRIDGE_REQUESTED = "JOURNEY_BRIDGE_REQUESTED"
JOURNEY_BRIDGE_SUCCESS = "JOURNEY_BRIDGE_SUCCESS"
JOURNEY_BRIDGE_FAILURE = "JOURNEY_BRIDGE_FAILURE"
JOURNEY_BRIDGE_LATENCY = "JOURNEY_BRIDGE_LATENCY"
JOURNEY_BRIDGE_EVENT_TYPES: tuple[str, ...] = (
    JOURNEY_BRIDGE_REQUESTED,
    JOURNEY_BRIDGE_SUCCESS,
    JOURNEY_BRIDGE_FAILURE,
    JOURNEY_BRIDGE_LATENCY,
)

# History Read Bridge observational events (MS-002 Directive 003).
HISTORY_BRIDGE_REQUESTED = "HISTORY_BRIDGE_REQUESTED"
HISTORY_BRIDGE_SUCCESS = "HISTORY_BRIDGE_SUCCESS"
HISTORY_BRIDGE_FAILURE = "HISTORY_BRIDGE_FAILURE"
HISTORY_BRIDGE_LATENCY = "HISTORY_BRIDGE_LATENCY"
HISTORY_BRIDGE_EVENT_TYPES: tuple[str, ...] = (
    HISTORY_BRIDGE_REQUESTED,
    HISTORY_BRIDGE_SUCCESS,
    HISTORY_BRIDGE_FAILURE,
    HISTORY_BRIDGE_LATENCY,
)

# Adaptive Shadow Execution observational events (MS-003 Directive 004 / A2).
ADAPTIVE_SHADOW_REQUESTED = "ADAPTIVE_SHADOW_REQUESTED"
ADAPTIVE_SHADOW_COMPLETED = "ADAPTIVE_SHADOW_COMPLETED"
ADAPTIVE_SHADOW_FAILED = "ADAPTIVE_SHADOW_FAILED"
ADAPTIVE_SHADOW_LATENCY = "ADAPTIVE_SHADOW_LATENCY"
ADAPTIVE_SHADOW_EVENT_TYPES: tuple[str, ...] = (
    ADAPTIVE_SHADOW_REQUESTED,
    ADAPTIVE_SHADOW_COMPLETED,
    ADAPTIVE_SHADOW_FAILED,
    ADAPTIVE_SHADOW_LATENCY,
)

# Explainability Gate observational events (MS-003 Directive 005 / A3).
EXPLAINABILITY_GATE_REQUESTED = "EXPLAINABILITY_GATE_REQUESTED"
EXPLAINABILITY_GATE_PASSED = "EXPLAINABILITY_GATE_PASSED"
EXPLAINABILITY_GATE_FAILED = "EXPLAINABILITY_GATE_FAILED"
EXPLAINABILITY_GATE_LATENCY = "EXPLAINABILITY_GATE_LATENCY"
EXPLAINABILITY_GATE_EVENT_TYPES: tuple[str, ...] = (
    EXPLAINABILITY_GATE_REQUESTED,
    EXPLAINABILITY_GATE_PASSED,
    EXPLAINABILITY_GATE_FAILED,
    EXPLAINABILITY_GATE_LATENCY,
)

# Adaptive Experience Port Cutover observational events (MS-003 Directive 006 / A4).
ADAPTIVE_ENGINE_REQUESTED = "ADAPTIVE_ENGINE_REQUESTED"
ADAPTIVE_ENGINE_SUCCESS = "ADAPTIVE_ENGINE_SUCCESS"
ADAPTIVE_ENGINE_FAILURE = "ADAPTIVE_ENGINE_FAILURE"
ADAPTIVE_ENGINE_FALLBACK = "ADAPTIVE_ENGINE_FALLBACK"
ADAPTIVE_ENGINE_LATENCY = "ADAPTIVE_ENGINE_LATENCY"
ADAPTIVE_ENGINE_EVENT_TYPES: tuple[str, ...] = (
    ADAPTIVE_ENGINE_REQUESTED,
    ADAPTIVE_ENGINE_SUCCESS,
    ADAPTIVE_ENGINE_FAILURE,
    ADAPTIVE_ENGINE_FALLBACK,
    ADAPTIVE_ENGINE_LATENCY,
)

# Adaptive Observational Traceability events (MS-003 Directive 007 / A5).
ADAPTIVE_TRACE_CREATED = "ADAPTIVE_TRACE_CREATED"
ADAPTIVE_TRACE_FAILED = "ADAPTIVE_TRACE_FAILED"
ADAPTIVE_TRACE_RECONSTRUCTED = "ADAPTIVE_TRACE_RECONSTRUCTED"
ADAPTIVE_TRACE_EVENT_TYPES: tuple[str, ...] = (
    ADAPTIVE_TRACE_CREATED,
    ADAPTIVE_TRACE_FAILED,
    ADAPTIVE_TRACE_RECONSTRUCTED,
)

# Adaptive Shadow Soak observational events (MS-003 Directive 008 / A6).
ADAPTIVE_SOAK_REQUESTED = "ADAPTIVE_SOAK_REQUESTED"
ADAPTIVE_SOAK_COMPLETED = "ADAPTIVE_SOAK_COMPLETED"
ADAPTIVE_SOAK_FAILED = "ADAPTIVE_SOAK_FAILED"
ADAPTIVE_SOAK_COMPARE = "ADAPTIVE_SOAK_COMPARE"
ADAPTIVE_ENGINE_SHADOW_COMPARE = "ADAPTIVE_ENGINE_SHADOW_COMPARE"
ADAPTIVE_SOAK_DRIFT = "ADAPTIVE_SOAK_DRIFT"
ADAPTIVE_SOAK_LATENCY = "ADAPTIVE_SOAK_LATENCY"
ADAPTIVE_SOAK_HEALTH = "ADAPTIVE_SOAK_HEALTH"
ADAPTIVE_SOAK_ROLLBACK_VERIFIED = "ADAPTIVE_SOAK_ROLLBACK_VERIFIED"
ADAPTIVE_SOAK_EVENT_TYPES: tuple[str, ...] = (
    ADAPTIVE_SOAK_REQUESTED,
    ADAPTIVE_SOAK_COMPLETED,
    ADAPTIVE_SOAK_FAILED,
    ADAPTIVE_SOAK_COMPARE,
    ADAPTIVE_ENGINE_SHADOW_COMPARE,
    ADAPTIVE_SOAK_DRIFT,
    ADAPTIVE_SOAK_LATENCY,
    ADAPTIVE_SOAK_HEALTH,
    ADAPTIVE_SOAK_ROLLBACK_VERIFIED,
)

# Twin Shadow Validation observational events (MS-004 Directive 008 / T6).
TWIN_SHADOW_REQUESTED = "TWIN_SHADOW_REQUESTED"
TWIN_SHADOW_COMPLETED = "TWIN_SHADOW_COMPLETED"
TWIN_SHADOW_FAILED = "TWIN_SHADOW_FAILED"
TWIN_SHADOW_STABILITY = "TWIN_SHADOW_STABILITY"
TWIN_SHADOW_DRIFT = "TWIN_SHADOW_DRIFT"
TWIN_SHADOW_LATENCY = "TWIN_SHADOW_LATENCY"
TWIN_SHADOW_HEALTH = "TWIN_SHADOW_HEALTH"
TWIN_SHADOW_ROLLBACK_VERIFIED = "TWIN_SHADOW_ROLLBACK_VERIFIED"
TWIN_SHADOW_EVENT_TYPES: tuple[str, ...] = (
    TWIN_SHADOW_REQUESTED,
    TWIN_SHADOW_COMPLETED,
    TWIN_SHADOW_FAILED,
    TWIN_SHADOW_STABILITY,
    TWIN_SHADOW_DRIFT,
    TWIN_SHADOW_LATENCY,
    TWIN_SHADOW_HEALTH,
    TWIN_SHADOW_ROLLBACK_VERIFIED,
)

# Strategy Shadow Validation observational events (MS-005 Directive 005 / S3).
STRATEGY_SHADOW_REQUESTED = "STRATEGY_SHADOW_REQUESTED"
STRATEGY_SHADOW_COMPLETED = "STRATEGY_SHADOW_COMPLETED"
STRATEGY_SHADOW_FAILED = "STRATEGY_SHADOW_FAILED"
STRATEGY_SHADOW_STABILITY = "STRATEGY_SHADOW_STABILITY"
STRATEGY_SHADOW_DRIFT = "STRATEGY_SHADOW_DRIFT"
STRATEGY_SHADOW_LATENCY = "STRATEGY_SHADOW_LATENCY"
STRATEGY_SHADOW_HEALTH = "STRATEGY_SHADOW_HEALTH"
STRATEGY_SHADOW_ROLLBACK_VERIFIED = "STRATEGY_SHADOW_ROLLBACK_VERIFIED"
STRATEGY_SHADOW_EVENT_TYPES: tuple[str, ...] = (
    STRATEGY_SHADOW_REQUESTED,
    STRATEGY_SHADOW_COMPLETED,
    STRATEGY_SHADOW_FAILED,
    STRATEGY_SHADOW_STABILITY,
    STRATEGY_SHADOW_DRIFT,
    STRATEGY_SHADOW_LATENCY,
    STRATEGY_SHADOW_HEALTH,
    STRATEGY_SHADOW_ROLLBACK_VERIFIED,
)

# Evidence Collection observational events (MS-006 E1).
EVIDENCE_COLLECTION_REQUESTED = "EVIDENCE_COLLECTION_REQUESTED"
EVIDENCE_COLLECTION_COMPLETED = "EVIDENCE_COLLECTION_COMPLETED"
EVIDENCE_COLLECTION_FAILED = "EVIDENCE_COLLECTION_FAILED"
EVIDENCE_COLLECTION_LATENCY = "EVIDENCE_COLLECTION_LATENCY"
EVIDENCE_COLLECTION_EVENT_TYPES: tuple[str, ...] = (
    EVIDENCE_COLLECTION_REQUESTED,
    EVIDENCE_COLLECTION_COMPLETED,
    EVIDENCE_COLLECTION_FAILED,
    EVIDENCE_COLLECTION_LATENCY,
)

# Experiment Assignment observational events (MS-006 E2).
EXPERIMENT_ASSIGNMENT_REQUESTED = "EXPERIMENT_ASSIGNMENT_REQUESTED"
EXPERIMENT_ASSIGNMENT_COMPLETED = "EXPERIMENT_ASSIGNMENT_COMPLETED"
EXPERIMENT_ASSIGNMENT_FAILED = "EXPERIMENT_ASSIGNMENT_FAILED"
EXPERIMENT_ASSIGNMENT_LATENCY = "EXPERIMENT_ASSIGNMENT_LATENCY"
EXPERIMENT_ASSIGNMENT_EVENT_TYPES: tuple[str, ...] = (
    EXPERIMENT_ASSIGNMENT_REQUESTED,
    EXPERIMENT_ASSIGNMENT_COMPLETED,
    EXPERIMENT_ASSIGNMENT_FAILED,
    EXPERIMENT_ASSIGNMENT_LATENCY,
)

# Policy Evaluation observational events (MS-006 E3).
EVIDENCE_EVAL_REQUESTED = "EVIDENCE_EVAL_REQUESTED"
EVIDENCE_EVAL_COMPLETED = "EVIDENCE_EVAL_COMPLETED"
EVIDENCE_EVAL_FAILED = "EVIDENCE_EVAL_FAILED"
EVIDENCE_EVAL_LATENCY = "EVIDENCE_EVAL_LATENCY"
EVIDENCE_EVAL_EVENT_TYPES: tuple[str, ...] = (
    EVIDENCE_EVAL_REQUESTED,
    EVIDENCE_EVAL_COMPLETED,
    EVIDENCE_EVAL_FAILED,
    EVIDENCE_EVAL_LATENCY,
)

# Analytics & Projection observational events (MS-006 E4).
EVIDENCE_ANALYTICS_REQUESTED = "EVIDENCE_ANALYTICS_REQUESTED"
EVIDENCE_ANALYTICS_COMPLETED = "EVIDENCE_ANALYTICS_COMPLETED"
EVIDENCE_ANALYTICS_FAILED = "EVIDENCE_ANALYTICS_FAILED"
EVIDENCE_ANALYTICS_LATENCY = "EVIDENCE_ANALYTICS_LATENCY"
EVIDENCE_ANALYTICS_EVENT_TYPES: tuple[str, ...] = (
    EVIDENCE_ANALYTICS_REQUESTED,
    EVIDENCE_ANALYTICS_COMPLETED,
    EVIDENCE_ANALYTICS_FAILED,
    EVIDENCE_ANALYTICS_LATENCY,
)

# Evidence Shadow Validation observational events (MS-006 Directive 007 / E5).
EVIDENCE_SHADOW_REQUESTED = "EVIDENCE_SHADOW_REQUESTED"
EVIDENCE_SHADOW_COMPLETED = "EVIDENCE_SHADOW_COMPLETED"
EVIDENCE_SHADOW_FAILED = "EVIDENCE_SHADOW_FAILED"
EVIDENCE_SHADOW_STABILITY = "EVIDENCE_SHADOW_STABILITY"
EVIDENCE_SHADOW_DRIFT = "EVIDENCE_SHADOW_DRIFT"
EVIDENCE_SHADOW_LATENCY = "EVIDENCE_SHADOW_LATENCY"
EVIDENCE_SHADOW_HEALTH = "EVIDENCE_SHADOW_HEALTH"
EVIDENCE_SHADOW_ROLLBACK_VERIFIED = "EVIDENCE_SHADOW_ROLLBACK_VERIFIED"
EVIDENCE_SHADOW_READINESS = "EVIDENCE_SHADOW_READINESS"
EVIDENCE_SHADOW_EVENT_TYPES: tuple[str, ...] = (
    EVIDENCE_SHADOW_REQUESTED,
    EVIDENCE_SHADOW_COMPLETED,
    EVIDENCE_SHADOW_FAILED,
    EVIDENCE_SHADOW_STABILITY,
    EVIDENCE_SHADOW_DRIFT,
    EVIDENCE_SHADOW_LATENCY,
    EVIDENCE_SHADOW_HEALTH,
    EVIDENCE_SHADOW_ROLLBACK_VERIFIED,
    EVIDENCE_SHADOW_READINESS,
)

# Experience Observability & Diagnostics (P2-MS007) — operational only.
EXPERIENCE_DIAG_JOURNEY_EVENT = "EXPERIENCE_DIAG_JOURNEY_EVENT"
EXPERIENCE_DIAG_OBSERVATION_PUBLISHED = "EXPERIENCE_DIAG_OBSERVATION_PUBLISHED"
EXPERIENCE_DIAG_EVIDENCE_ACK = "EXPERIENCE_DIAG_EVIDENCE_ACK"
EXPERIENCE_DIAG_EVENT_TYPES: tuple[str, ...] = (
    EXPERIENCE_DIAG_JOURNEY_EVENT,
    EXPERIENCE_DIAG_OBSERVATION_PUBLISHED,
    EXPERIENCE_DIAG_EVIDENCE_ACK,
)

# EP-002.1 consumer-chain observability for Twin-gated build_* APIs.
# EP-002.2 adds Foundation assemble / share-hit observation.
# EP-002.3 adds Twin & Authority non-production soak events.
CONSUMER_CHAIN_REQUESTED = "CONSUMER_CHAIN_REQUESTED"
CONSUMER_CHAIN_COMPLETED = "CONSUMER_CHAIN_COMPLETED"
CONSUMER_CHAIN_FAILED = "CONSUMER_CHAIN_FAILED"
CONSUMER_CHAIN_LATENCY = "CONSUMER_CHAIN_LATENCY"
CONSUMER_CHAIN_DUAL_RUN = "CONSUMER_CHAIN_DUAL_RUN"
CONSUMER_CHAIN_CUTOVER = "CONSUMER_CHAIN_CUTOVER"
CONSUMER_CHAIN_FOUNDATION_ASSEMBLE = "CONSUMER_CHAIN_FOUNDATION_ASSEMBLE"
CONSUMER_CHAIN_SOAK_REQUESTED = "CONSUMER_CHAIN_SOAK_REQUESTED"
CONSUMER_CHAIN_SOAK_COMPLETED = "CONSUMER_CHAIN_SOAK_COMPLETED"
CONSUMER_CHAIN_SOAK_FAILED = "CONSUMER_CHAIN_SOAK_FAILED"
CONSUMER_CHAIN_SOAK_HEALTH = "CONSUMER_CHAIN_SOAK_HEALTH"
CONSUMER_CHAIN_SOAK_MATRIX = "CONSUMER_CHAIN_SOAK_MATRIX"
CONSUMER_CHAIN_SOAK_ROLLBACK_VERIFIED = "CONSUMER_CHAIN_SOAK_ROLLBACK_VERIFIED"
CONSUMER_CHAIN_EVENT_TYPES: tuple[str, ...] = (
    CONSUMER_CHAIN_REQUESTED,
    CONSUMER_CHAIN_COMPLETED,
    CONSUMER_CHAIN_FAILED,
    CONSUMER_CHAIN_LATENCY,
    CONSUMER_CHAIN_DUAL_RUN,
    CONSUMER_CHAIN_CUTOVER,
    CONSUMER_CHAIN_FOUNDATION_ASSEMBLE,
    CONSUMER_CHAIN_SOAK_REQUESTED,
    CONSUMER_CHAIN_SOAK_COMPLETED,
    CONSUMER_CHAIN_SOAK_FAILED,
    CONSUMER_CHAIN_SOAK_HEALTH,
    CONSUMER_CHAIN_SOAK_MATRIX,
    CONSUMER_CHAIN_SOAK_ROLLBACK_VERIFIED,
)

# Core + Student Experience surface events (V2-017 / V2-018).
EVENT_TYPES: tuple[str, ...] = tuple(
    dict.fromkeys(
        (
            EVIDENCE_RECORDED,
            TWIN_UPDATED,
            ADAPTIVE_DECISION_GENERATED,
            MISSION_UPDATED,
            CURRICULUM_PUBLISHED,
            CURRICULUM_VALIDATED,
            LEARNING_SESSION_COMPLETED,
            *EXPERIENCE_EVENT_TYPES,
            *MISSION_BRIDGE_EVENT_TYPES,
            *MISSION_START_BRIDGE_EVENT_TYPES,
            *MISSION_RESUME_BRIDGE_EVENT_TYPES,
            *SESSION_COMPLETION_BRIDGE_EVENT_TYPES,
            *RECOMMENDATION_BRIDGE_EVENT_TYPES,
            *JOURNEY_BRIDGE_EVENT_TYPES,
            *HISTORY_BRIDGE_EVENT_TYPES,
            *ADAPTIVE_SHADOW_EVENT_TYPES,
            *EXPLAINABILITY_GATE_EVENT_TYPES,
            *ADAPTIVE_ENGINE_EVENT_TYPES,
            *ADAPTIVE_TRACE_EVENT_TYPES,
            *ADAPTIVE_SOAK_EVENT_TYPES,
            *TWIN_SHADOW_EVENT_TYPES,
            *STRATEGY_SHADOW_EVENT_TYPES,
            *EVIDENCE_COLLECTION_EVENT_TYPES,
            *EXPERIMENT_ASSIGNMENT_EVENT_TYPES,
            *EVIDENCE_EVAL_EVENT_TYPES,
            *EVIDENCE_ANALYTICS_EVENT_TYPES,
            *EVIDENCE_SHADOW_EVENT_TYPES,
            *EXPERIENCE_DIAG_EVENT_TYPES,
            *CONSUMER_CHAIN_EVENT_TYPES,
        )
    )
)


def evidence_recorded(
    payload: dict,
    **kwargs,
) -> IntegrationEvent:
    """Build an EvidenceRecorded event."""
    return IntegrationEvent.create(EVIDENCE_RECORDED, payload, **kwargs)


def twin_updated(payload: dict, **kwargs) -> IntegrationEvent:
    """Build a TwinUpdated event."""
    return IntegrationEvent.create(TWIN_UPDATED, payload, **kwargs)


def adaptive_decision_generated(payload: dict, **kwargs) -> IntegrationEvent:
    """Build an AdaptiveDecisionGenerated event."""
    return IntegrationEvent.create(
        ADAPTIVE_DECISION_GENERATED, payload, **kwargs
    )


def mission_updated(payload: dict, **kwargs) -> IntegrationEvent:
    """Build a MissionUpdated event."""
    return IntegrationEvent.create(MISSION_UPDATED, payload, **kwargs)


def curriculum_published(payload: dict, **kwargs) -> IntegrationEvent:
    """Build a CurriculumPublished event."""
    return IntegrationEvent.create(CURRICULUM_PUBLISHED, payload, **kwargs)


def curriculum_validated(payload: dict, **kwargs) -> IntegrationEvent:
    """Build a CurriculumValidated event."""
    return IntegrationEvent.create(CURRICULUM_VALIDATED, payload, **kwargs)


def learning_session_completed(payload: dict, **kwargs) -> IntegrationEvent:
    """Build a LearningSessionCompleted event."""
    return IntegrationEvent.create(
        LEARNING_SESSION_COMPLETED, payload, **kwargs
    )
