"""Database models."""

from app.models.adaptive_mission import (
    AmeAdaptiveMission,
    AmeMissionCompletion,
    AmeMissionFeedback,
    AmeMissionHistory,
    AmeMissionProgress,
    AmeMissionStep,
)
from app.models.alpha_infrastructure import (
    AlphaFeedbackSubmission,
    PresentationEvent,
)
from app.models.analytics_events import (
    AnalyticsAuditLogRecord,
    AnalyticsEventRecord,
    AnalyticsOutboxRecord,
)
from app.models.assessment_pipeline import (
    ApActivityAttempt,
    ApAssessmentEvent,
    ApAssessmentResult,
    ApLearningFeedback,
    ApMissionAssessmentLink,
    ApPerformanceSummary,
)
from app.models.curriculum import Curriculum, Section, Topic
from app.models.curriculum_intelligence import (
    CipAuditEvent,
    CipConfidenceFactor,
    CipConfidenceRecord,
    CipCurriculumEntity,
    CipEmbeddingRecord,
    CipExtractedBlock,
    CipExtractedDocument,
    CipExtractedPage,
    CipKnowledgeRelation,
    CipLocalVectorEntry,
    CipProcessingEvent,
    CipProcessingJob,
    CipProvenanceEvidence,
    CipProvenanceRecord,
    CipQualityMetrics,
    CipRetrievalLog,
    CipReviewRecord,
    CipStructuralNode,
    CipValidationIssue,
    CipValidationReport,
)
from app.models.curriculum_knowledge_graph import (
    CkgDefinition,
    CkgEdge,
    CkgEditionSnapshot,
    CkgEditorialAuditEvent,
    CkgFormula,
    CkgGraphEdition,
    CkgIdAlias,
    CkgLearningObjective,
    CkgLoLink,
    CkgNodeProvenance,
    CkgNodeReviewState,
    CkgPracticeExercise,
    CkgPublicationRecord,
    CkgReadingReference,
    CkgSection,
    CkgSubject,
    CkgSubsection,
    CkgSyllabusOutcome,
    CkgTopic,
    CkgValidationReport,
    CkgWorkedExample,
)
from app.models.curriculum_studio_foundation import (
    PublishedCurriculumPackage,
    StudioFoundationAuditEvent,
    StudioFoundationDocument,
    StudioFoundationSubject,
    StudioFoundationVersion,
)
from app.models.decision import Decision
from app.models.decision_journal import (
    DecisionJournalEntry,
    DecisionJournalEvidenceEvent,
)
from app.models.educational_feedback import EducationalFeedbackReview
from app.models.educational_reasoning import (
    DecisionRecord,
    EducationalReasoningRun,
    EducationalRuleExecution,
    ReasoningExplanation,
)
from app.models.educational_reasoning_engine import EreEducationalDecision
from app.models.educational_runtime_engine import (
    RuntimeEducationalEvent,
    RuntimeEnrolment,
    RuntimeMissionInstance,
    RuntimeStudyPlanInstance,
)
from app.models.identity import UserCapability, UserRole
from app.models.intelligent_tutor import (
    TutorExplanationRow,
    TutorFeedbackRow,
    TutorMessageRow,
    TutorSessionRow,
)
from app.models.learner_lifecycle import LlpLifecycleOperation
from app.models.learning import LearningObjective, Mistake, StudyAttempt
from app.models.learning_evidence import LeeEvidenceEvent
from app.models.learning_graph import (
    LgGraphEdge,
    LgGraphNode,
    LgGraphSnapshot,
    LgGraphUpdateHistory,
    LgLearningGraph,
)
from app.models.mission import Mission, MissionTask
from app.models.platform_integration import RuntimeEnrolmentRoutingAudit
from app.models.recommendation_commitment import RecommendationCommitment
from app.models.research_feedback import (
    FEATURE_AREA_CHOICES,
    FINDING_STATUSES,
    SEVERITY_CHOICES,
    WORKFLOW_STATUSES,
    ResearchContribution,
    ResearchContributorBadge,
    ResearchFeedbackReview,
    ResearchFeedbackStatusTransition,
    ResearchFeedbackSubmission,
    ResearchFounderNote,
    ResearchProductFinding,
    ResearchProductFindingLink,
    ResearchProductFindingStatusTransition,
)
from app.models.student_curriculum_binding import (
    SciCurriculumNodeState,
    SciStudentCurriculumInstance,
)
from app.models.student_digital_twin import (
    SdtKnowledgeGap,
    SdtLearningStateSnapshot,
    SdtMasteryRecord,
    SdtObservation,
    SdtPrediction,
    SdtReasoningHistory,
    SdtRecommendation,
    SdtStudentDigitalTwin,
)
from app.models.study_plan import StudyPlan, WeekPlan
from app.models.subject import Subject
from app.models.topic_progress import TopicProgress
from app.models.twin_inference import TieNodeBelief
from app.models.twin_snapshot import TwinSnapshot
from app.models.user import User
from app.models.v2_aggregate import (
    V2AggregateDocument,
    V2AggregateSnapshot,
    V2EvidenceEvent,
)
from app.models.vision_journal import (
    RELATION_TYPES,
    TARGET_VERSIONS,
    VISION_CATEGORIES,
    VISION_STATUSES,
    VisionEntry,
    VisionEntryPromotion,
    VisionEntryRelation,
    VisionEntryStatusTransition,
)

__all__ = [
    "User",
    "UserRole",
    "UserCapability",
    "Subject",
    "Mission",
    "MissionTask",
    "StudyPlan",
    "WeekPlan",
    "Curriculum",
    "Section",
    "Topic",
    "CkgGraphEdition",
    "CkgSubject",
    "CkgTopic",
    "CkgSection",
    "CkgSubsection",
    "CkgLearningObjective",
    "CkgDefinition",
    "CkgFormula",
    "CkgWorkedExample",
    "CkgPracticeExercise",
    "CkgReadingReference",
    "CkgSyllabusOutcome",
    "CkgLoLink",
    "CkgEdge",
    "CkgIdAlias",
    "CkgNodeProvenance",
    "CkgValidationReport",
    "CkgNodeReviewState",
    "CkgEditorialAuditEvent",
    "CkgPublicationRecord",
    "CkgEditionSnapshot",
    "StudioFoundationSubject",
    "StudioFoundationVersion",
    "StudioFoundationDocument",
    "StudioFoundationAuditEvent",
    "PublishedCurriculumPackage",
    "CipProcessingJob",
    "CipProcessingEvent",
    "CipExtractedDocument",
    "CipExtractedPage",
    "CipExtractedBlock",
    "CipStructuralNode",
    "CipCurriculumEntity",
    "CipKnowledgeRelation",
    "CipProvenanceRecord",
    "CipProvenanceEvidence",
    "CipConfidenceRecord",
    "CipConfidenceFactor",
    "CipReviewRecord",
    "CipValidationReport",
    "CipValidationIssue",
    "CipAuditEvent",
    "CipQualityMetrics",
    "CipEmbeddingRecord",
    "CipLocalVectorEntry",
    "CipRetrievalLog",
    "SciStudentCurriculumInstance",
    "SciCurriculumNodeState",
    "LeeEvidenceEvent",
    "LlpLifecycleOperation",
    "TieNodeBelief",
    "EreEducationalDecision",
    "SdtStudentDigitalTwin",
    "SdtObservation",
    "SdtMasteryRecord",
    "SdtKnowledgeGap",
    "SdtLearningStateSnapshot",
    "SdtRecommendation",
    "SdtPrediction",
    "SdtReasoningHistory",
    "EducationalReasoningRun",
    "EducationalRuleExecution",
    "ReasoningExplanation",
    "DecisionRecord",
    "LgLearningGraph",
    "LgGraphNode",
    "LgGraphEdge",
    "LgGraphSnapshot",
    "LgGraphUpdateHistory",
    "AmeAdaptiveMission",
    "AmeMissionStep",
    "AmeMissionProgress",
    "AmeMissionHistory",
    "AmeMissionFeedback",
    "AmeMissionCompletion",
    "ApAssessmentEvent",
    "ApAssessmentResult",
    "ApLearningFeedback",
    "ApMissionAssessmentLink",
    "ApActivityAttempt",
    "ApPerformanceSummary",
    "TutorSessionRow",
    "TutorMessageRow",
    "TutorExplanationRow",
    "TutorFeedbackRow",
    "RuntimeEnrolment",
    "RuntimeStudyPlanInstance",
    "RuntimeMissionInstance",
    "RuntimeEducationalEvent",
    "RuntimeEnrolmentRoutingAudit",
    "TopicProgress",
    "StudyAttempt",
    "LearningObjective",
    "Mistake",
    "Decision",
    "DecisionJournalEntry",
    "DecisionJournalEvidenceEvent",
    "EducationalFeedbackReview",
    "RecommendationCommitment",
    "TwinSnapshot",
    "V2AggregateDocument",
    "V2AggregateSnapshot",
    "V2EvidenceEvent",
    "PresentationEvent",
    "AlphaFeedbackSubmission",
    "AnalyticsEventRecord",
    "AnalyticsOutboxRecord",
    "AnalyticsAuditLogRecord",
    "ResearchFeedbackSubmission",
    "ResearchContribution",
    "ResearchContributorBadge",
    "ResearchFeedbackReview",
    "ResearchFeedbackStatusTransition",
    "ResearchFounderNote",
    "ResearchProductFinding",
    "ResearchProductFindingLink",
    "ResearchProductFindingStatusTransition",
    "WORKFLOW_STATUSES",
    "SEVERITY_CHOICES",
    "FEATURE_AREA_CHOICES",
    "FINDING_STATUSES",
    "VisionEntry",
    "VisionEntryStatusTransition",
    "VisionEntryRelation",
    "VisionEntryPromotion",
    "VISION_CATEGORIES",
    "VISION_STATUSES",
    "TARGET_VERSIONS",
    "RELATION_TYPES",
]
