"""Learning Feedback Loop (EP-003.4).

Neutral educational feedback capability that records student interactions
with plans, recommendations, and study activities as observed evidence only.

Feature flag: ``KWALITEC_LEARNING_FEEDBACK`` / ``ENABLE_LEARNING_FEEDBACK``
(default OFF). Independently controllable from Experience Feedback display
and Evidence Platform flags.

Does not make educational decisions. Does not change Recommendation,
Readiness, or Planning authority. Does not alter RuntimeAPresentationAdapter.
"""

from __future__ import annotations

from .contracts import (
    ALLOWED_CLAIM_BOUNDARIES,
    ALLOWED_SOURCE_AUTHORITIES,
    AUTHORITY_LEARNING_FEEDBACK,
    CLAIM_OBSERVED_BEHAVIOUR,
    CLAIM_PLAN_INTERACTION,
    CLAIM_PREFERENCE_JOURNAL,
    CLAIM_STUDY_HABIT_SIGNAL,
    CONTRACT_VERSION,
    EVIDENCE_KIND_OBSERVED,
    FEEDBACK_EVENT_COMMITMENT_COMPLETED,
    FEEDBACK_EVENT_COMMITMENT_CONFIRMED,
    FEEDBACK_EVENT_COMMITMENT_DEFERRED,
    FEEDBACK_EVENT_PLAN_COMPLETED,
    FEEDBACK_EVENT_RECOMMENDATION_ACCEPTED,
    FEEDBACK_EVENT_RECOMMENDATION_DISMISSED,
    FEEDBACK_EVENT_RECOVERY_APPLIED,
    FEEDBACK_EVENT_REFLECTION_VIEWED,
    FEEDBACK_EVENT_REVISION_ADHERED,
    FEEDBACK_EVENT_REVISION_DEFERRED,
    FEEDBACK_EVENT_SESSION_MISSED,
    FEEDBACK_EVENT_STUDY_CONSISTENCY,
    FORBIDDEN_INFERENCE_KEYS,
    OBSERVABLE_FEEDBACK_EVENTS,
    REASON_FLAG_OFF,
    REASON_FORBIDDEN_INFERENCE,
    REASON_RECORDER_ERROR,
    REASON_SCHEMA_INVALID,
    REASON_UNKNOWN_EVENT,
    REASON_UNKNOWN_SOURCE,
    RECORD_STATUS_FAILED,
    RECORD_STATUS_RECORDED,
    RECORD_STATUS_SKIPPED,
    RECORD_STATUSES,
    SOURCE_PLANNING,
    SOURCE_READINESS,
    SOURCE_RECOMMENDATION,
    FeedbackRecordResult,
    LearningFeedbackEvent,
    LearningFeedbackRecorderPort,
    deterministic_feedback_id,
    serialize_canonical,
)
from .emitter import (
    bind_learning_feedback_recorder,
    emit_learning_feedback,
    emit_plan_completed_feedback,
    emit_planning_recovery_feedback,
    emit_recommendation_decision_feedback,
    emit_revision_feedback,
    emit_study_consistency_feedback,
    get_learning_feedback_recorder,
)
from .recorder import (
    LearningFeedbackRecorder,
    build_learning_feedback_recorder,
)

__all__ = [
    "ALLOWED_CLAIM_BOUNDARIES",
    "ALLOWED_SOURCE_AUTHORITIES",
    "AUTHORITY_LEARNING_FEEDBACK",
    "CLAIM_OBSERVED_BEHAVIOUR",
    "CLAIM_PLAN_INTERACTION",
    "CLAIM_PREFERENCE_JOURNAL",
    "CLAIM_STUDY_HABIT_SIGNAL",
    "CONTRACT_VERSION",
    "EVIDENCE_KIND_OBSERVED",
    "FEEDBACK_EVENT_COMMITMENT_COMPLETED",
    "FEEDBACK_EVENT_COMMITMENT_CONFIRMED",
    "FEEDBACK_EVENT_COMMITMENT_DEFERRED",
    "FEEDBACK_EVENT_PLAN_COMPLETED",
    "FEEDBACK_EVENT_RECOMMENDATION_ACCEPTED",
    "FEEDBACK_EVENT_RECOMMENDATION_DISMISSED",
    "FEEDBACK_EVENT_RECOVERY_APPLIED",
    "FEEDBACK_EVENT_REFLECTION_VIEWED",
    "FEEDBACK_EVENT_REVISION_ADHERED",
    "FEEDBACK_EVENT_REVISION_DEFERRED",
    "FEEDBACK_EVENT_SESSION_MISSED",
    "FEEDBACK_EVENT_STUDY_CONSISTENCY",
    "FORBIDDEN_INFERENCE_KEYS",
    "OBSERVABLE_FEEDBACK_EVENTS",
    "RECORD_STATUS_FAILED",
    "RECORD_STATUS_RECORDED",
    "RECORD_STATUS_SKIPPED",
    "RECORD_STATUSES",
    "REASON_FLAG_OFF",
    "REASON_FORBIDDEN_INFERENCE",
    "REASON_RECORDER_ERROR",
    "REASON_SCHEMA_INVALID",
    "REASON_UNKNOWN_EVENT",
    "REASON_UNKNOWN_SOURCE",
    "SOURCE_PLANNING",
    "SOURCE_READINESS",
    "SOURCE_RECOMMENDATION",
    "FeedbackRecordResult",
    "LearningFeedbackEvent",
    "LearningFeedbackRecorder",
    "LearningFeedbackRecorderPort",
    "bind_learning_feedback_recorder",
    "build_learning_feedback_recorder",
    "deterministic_feedback_id",
    "emit_learning_feedback",
    "emit_plan_completed_feedback",
    "emit_planning_recovery_feedback",
    "emit_recommendation_decision_feedback",
    "emit_revision_feedback",
    "emit_study_consistency_feedback",
    "get_learning_feedback_recorder",
    "serialize_canonical",
]
