"""Recommendation Policy Framework package (P3-MS003 / P3-MS004).

Declarative, versioned policy that defines when and how approved advisory
information may influence Runtime A recommendations.

Feature flags (independent, default OFF):

- ``KWALITEC_RECOMMENDATION_POLICY`` / ``ENABLE_RECOMMENDATION_POLICY``
- ``KWALITEC_POLICY_WEIGHTING`` / ``ENABLE_POLICY_WEIGHTING``

Policy remains external to recommendation logic. Runtime A is the sole
educational decision authority. P3-MS004 permits applying exactly one
bounded weighting rule (``consistency_summary``) under the weighting flag.
"""

from __future__ import annotations

from .contracts import (
    APPROVED_WEIGHT_ADVISORY_FIELDS,
    AUTHORITY_RECOMMENDATION_POLICY,
    AUTHORITY_RUNTIME_A,
    DEFAULT_ADVISORY_FIELD,
    DEFAULT_ADVISORY_RULE_ID,
    DEFAULT_APPLIED_WEIGHTING_RULE_ID,
    DEFAULT_MAX_WEIGHT_ADJUSTMENT,
    DEFAULT_POLICY_ID,
    DEFAULT_POLICY_VERSION,
    DEFAULT_STREAK_SCALE,
    DEFAULT_WEIGHT_BASE,
    DEFAULT_WEIGHT_DIVERGENCE_TOLERANCE,
    DEFAULT_WEIGHT_MAX_AGE_HOURS,
    DEFAULT_WEIGHT_ROLLOUT_PERCENTAGE,
    DEFAULT_WEIGHT_ROLLOUT_SALT,
    DEFAULT_WEIGHTING_POLICY_ID,
    DEFAULT_WEIGHTING_POLICY_VERSION,
    DEFAULT_WEIGHTING_RULE_ID,
    INFLUENCE_ANNOTATE,
    INFLUENCE_MODES,
    INFLUENCE_PERMIT,
    INVALID_STATE,
    POLICY_ERROR_CODES,
    POLICY_EXPLAINABILITY_KEY,
    POLICY_WEIGHT_APPLICATION_VERSION,
    PRIORITY_BASE_WEIGHTS,
    REASON_ACTIVATION_CONSTRAINTS,
    REASON_DUPLICATE_RULE_ID,
    REASON_EFFECTIVE_FROM_FUTURE,
    REASON_EMPTY_RULE_ID,
    REASON_FLAG_OFF,
    REASON_NO_RULES_APPLICABLE,
    REASON_POLICY_INVALID,
    REASON_POLICY_MISSING,
    REASON_RULES_RESOLVED,
    REASON_UNKNOWN_INFLUENCE_MODE,
    REASON_WEIGHT_ADVISORY_FIELD_MISSING,
    REASON_WEIGHT_ADVISORY_MISSING,
    REASON_WEIGHT_ADVISORY_STALE,
    REASON_WEIGHT_APPLIED,
    REASON_WEIGHT_BOUNDS_INVALID,
    REASON_WEIGHT_DENIED,
    REASON_WEIGHT_FIELD_NOT_APPROVED,
    REASON_WEIGHT_NO_RULE,
    REASON_WEIGHT_ROLLOUT_EXCLUDED,
    REASON_WEIGHT_SIMULATION_DIVERGENCE,
    REASON_WEIGHTING_FLAG_OFF,
    REASON_WEIGHTING_NOT_APPLIED,
    RECOMMENDATION_POLICY_VERSION,
    RULE_KIND_ADVISORY,
    RULE_KIND_WEIGHTING,
    RULE_KINDS,
    UNAVAILABLE,
    WEIGHT_EXPLAINABILITY_KEY,
    AdvisoryRule,
    PolicyDecision,
    PolicyRuleResolution,
    RecommendationPolicy,
    RecommendationPolicyExplainability,
    WeightApplication,
    WeightingRule,
    build_default_recommendation_policy,
    build_default_weighting_policy,
    clamp_weight_adjustment,
    compute_consistency_weight_delta,
    deterministic_weight_application_id,
    explainability_fields_present,
    explainability_from_decision,
    explainability_from_weight_application,
    priority_base_weight,
    serialize_canonical,
    snapshot_explainability_list,
    snapshot_mapping,
    validate_recommendation_policy,
    weight_explainability_fields_present,
)
from .engine import (
    ENGINE_ID,
    ENGINE_VERSION,
    SERVICE_ID,
    SOURCE_SERVICE,
    RecommendationPolicyEngine,
    build_recommendation_policy_engine,
    resolve_recommendation_policy,
    resolve_weighting_policy,
    student_in_weight_rollout,
)

__all__ = [
    "APPROVED_WEIGHT_ADVISORY_FIELDS",
    "AUTHORITY_RECOMMENDATION_POLICY",
    "AUTHORITY_RUNTIME_A",
    "DEFAULT_ADVISORY_FIELD",
    "DEFAULT_ADVISORY_RULE_ID",
    "DEFAULT_APPLIED_WEIGHTING_RULE_ID",
    "DEFAULT_MAX_WEIGHT_ADJUSTMENT",
    "DEFAULT_POLICY_ID",
    "DEFAULT_POLICY_VERSION",
    "DEFAULT_STREAK_SCALE",
    "DEFAULT_WEIGHTING_POLICY_ID",
    "DEFAULT_WEIGHTING_POLICY_VERSION",
    "DEFAULT_WEIGHTING_RULE_ID",
    "DEFAULT_WEIGHT_BASE",
    "DEFAULT_WEIGHT_DIVERGENCE_TOLERANCE",
    "DEFAULT_WEIGHT_MAX_AGE_HOURS",
    "DEFAULT_WEIGHT_ROLLOUT_PERCENTAGE",
    "DEFAULT_WEIGHT_ROLLOUT_SALT",
    "ENGINE_ID",
    "ENGINE_VERSION",
    "INFLUENCE_ANNOTATE",
    "INFLUENCE_MODES",
    "INFLUENCE_PERMIT",
    "INVALID_STATE",
    "POLICY_ERROR_CODES",
    "POLICY_EXPLAINABILITY_KEY",
    "POLICY_WEIGHT_APPLICATION_VERSION",
    "PRIORITY_BASE_WEIGHTS",
    "REASON_ACTIVATION_CONSTRAINTS",
    "REASON_DUPLICATE_RULE_ID",
    "REASON_EMPTY_RULE_ID",
    "REASON_EFFECTIVE_FROM_FUTURE",
    "REASON_FLAG_OFF",
    "REASON_NO_RULES_APPLICABLE",
    "REASON_POLICY_INVALID",
    "REASON_POLICY_MISSING",
    "REASON_RULES_RESOLVED",
    "REASON_UNKNOWN_INFLUENCE_MODE",
    "REASON_WEIGHTING_FLAG_OFF",
    "REASON_WEIGHTING_NOT_APPLIED",
    "REASON_WEIGHT_ADVISORY_FIELD_MISSING",
    "REASON_WEIGHT_ADVISORY_MISSING",
    "REASON_WEIGHT_ADVISORY_STALE",
    "REASON_WEIGHT_APPLIED",
    "REASON_WEIGHT_BOUNDS_INVALID",
    "REASON_WEIGHT_DENIED",
    "REASON_WEIGHT_FIELD_NOT_APPROVED",
    "REASON_WEIGHT_NO_RULE",
    "REASON_WEIGHT_ROLLOUT_EXCLUDED",
    "REASON_WEIGHT_SIMULATION_DIVERGENCE",
    "RECOMMENDATION_POLICY_VERSION",
    "RULE_KIND_ADVISORY",
    "RULE_KIND_WEIGHTING",
    "RULE_KINDS",
    "SERVICE_ID",
    "SOURCE_SERVICE",
    "UNAVAILABLE",
    "WEIGHT_EXPLAINABILITY_KEY",
    "AdvisoryRule",
    "PolicyDecision",
    "PolicyRuleResolution",
    "RecommendationPolicy",
    "RecommendationPolicyEngine",
    "RecommendationPolicyExplainability",
    "WeightApplication",
    "WeightingRule",
    "build_default_recommendation_policy",
    "build_default_weighting_policy",
    "build_recommendation_policy_engine",
    "clamp_weight_adjustment",
    "compute_consistency_weight_delta",
    "deterministic_weight_application_id",
    "explainability_fields_present",
    "explainability_from_decision",
    "explainability_from_weight_application",
    "priority_base_weight",
    "resolve_recommendation_policy",
    "resolve_weighting_policy",
    "serialize_canonical",
    "snapshot_explainability_list",
    "snapshot_mapping",
    "student_in_weight_rollout",
    "validate_recommendation_policy",
    "weight_explainability_fields_present",
]
