"""V3 design-system components — pure visual contracts only.

Legacy rejected components remain importable here for unmigrated surfaces.
DX-006B migrations MUST import from presentation.design_system.foundation.
"""

from __future__ import annotations

from presentation.design_system.components.buttons import (
    Button,
    ButtonVariant,
    danger_button,
    ghost_button,
    primary_button,
    secondary_button,
)
from presentation.design_system.components.cards import (
    Card,
    CardVariant,
    MissionCard,
    ProgressCard,
    RecommendationCard,
)
from presentation.design_system.components.feedback import (
    EmptyState,
    LoadingState,
    Modal,
    Skeleton,
    SkeletonVariant,
    Toast,
    ToastTone,
)
from presentation.design_system.components.forms import (
    Checkbox,
    ErrorState,
    FieldState,
    Input,
    Radio,
    SearchInput,
    Select,
    Spinner,
    Textarea,
    Toggle,
)
from presentation.design_system.components.layout_primitives import (
    ContentContainer,
    DataList,
    DataTable,
    Inline,
    LayoutGrid,
    Page,
    Panel,
    PrimaryActionStrip,
    SearchBar,
    Stack,
    StackDirection,
    Toolbar,
)
from presentation.design_system.components.markers import (
    Badge,
    Chip,
    Divider,
    Tag,
    Tone,
)
from presentation.design_system.components.operational import (
    BlockingFinding,
    BlockingFindings,
    CurrentWork,
    Disclosure,
    EmptyOperationalState,
    FeedbackBlock,
    LearningQueue,
    MissionPanel,
    PersistentContext,
    PublicationQueue,
    PublicationStatus,
    QueueRow,
    RecentProgress,
    RecentPublications,
    SearchResults,
    SessionContext,
    StageIndicator,
)
from presentation.design_system.components.progress import (
    ProgressBar,
    ProgressRing,
    StatisticTile,
)
from presentation.design_system.components.section import PageHeader, Section
from presentation.design_system.components.structure import (
    Accordion,
    AccordionPanel,
    Stepper,
    StepperStep,
    Timeline,
    TimelineItem,
)

__all__ = [
    "Accordion",
    "AccordionPanel",
    "Badge",
    "BlockingFinding",
    "BlockingFindings",
    "Button",
    "ButtonVariant",
    "Card",
    "CardVariant",
    "Checkbox",
    "Chip",
    "ContentContainer",
    "CurrentWork",
    "DataList",
    "DataTable",
    "Disclosure",
    "Divider",
    "EmptyOperationalState",
    "EmptyState",
    "ErrorState",
    "FeedbackBlock",
    "FieldState",
    "Inline",
    "Input",
    "LayoutGrid",
    "LearningQueue",
    "LoadingState",
    "MissionCard",
    "MissionPanel",
    "Modal",
    "Page",
    "PageHeader",
    "Panel",
    "PersistentContext",
    "PrimaryActionStrip",
    "ProgressBar",
    "ProgressCard",
    "ProgressRing",
    "PublicationQueue",
    "PublicationStatus",
    "QueueRow",
    "Radio",
    "RecentProgress",
    "RecentPublications",
    "RecommendationCard",
    "SearchBar",
    "SearchInput",
    "SearchResults",
    "Section",
    "Select",
    "SessionContext",
    "Skeleton",
    "SkeletonVariant",
    "Spinner",
    "Stack",
    "StackDirection",
    "StageIndicator",
    "StatisticTile",
    "Stepper",
    "StepperStep",
    "Tag",
    "Textarea",
    "Timeline",
    "TimelineItem",
    "Toast",
    "ToastTone",
    "Toggle",
    "Tone",
    "Toolbar",
    "danger_button",
    "ghost_button",
    "primary_button",
    "secondary_button",
]
